### ISSUE TITLE
Code in 'CrashReporter' doesn't work with App Sandbox

### ISSUE THREAD

**Issue by elemans** [Ranchero-Software/NetNewsWire#1222]
Path "~/Library/Logs/DiagnosticReports/" used in struct 'CrashReporter' is outside the App Sandbox, so this will not work in apps with Sandbox enabled.

**Comment by danielpunkass** [comment]
Good catch.

**Comment by danielpunkass** [comment]
In my own sandboxed apps I work around this limitation by bundling PLCrashReporter, which generates and writes crash logs into the app's sandbox container. That might be more trouble than it's worth, at least for now, in NetNewsWire.

Maybe a good compromise for us would be to add an entitlement permitting access to ~/Library/Logs/DiagnosticReports, so that we can continue to work even when sandboxed. I propose we make an effort to include this when submitting to the App Store, but don't sweat it too much if we are not allowed that access. We can rely on App Store generated crash reports for the App Store at least for now.

**Comment by brentsimmons** [comment]
Let’s not include the crash reporter with the MAS build.

Let’s *do* include the crash reporter with the sandboxed, direct-download build.

**Comment by danielpunkass** [comment]
@brentsimmons Did you end up keeping the crash reporter working in the sandboxed build? I think this can be closed.

**Comment by brentsimmons** [comment]
Yup — we have this working via other means now.
