### ISSUE TITLE
iOS Timeline: Back swipe animation error in smart feeds

### ISSUE THREAD

**Issue by nostodnayr** [Ranchero-Software/NetNewsWire#1238]
1. Choose a well-populated smart feed
2. Scroll down the list by several items
3. Swipe from the left edge to go back

The animation renders the title bar under the timeline items.

(iPhone X, iOS 13.2)
![swipe-back](https://user-images.githubusercontent.com/2190735/68078921-b675e180-fe23-11e9-8af0-9c51031cb72c.png)

**Comment by nostodnayr** [comment]
This also happens with regular feeds, if they’re in a On My [Device] account it seems.

**Comment by vincode-io** [comment]
I'm going to reopen this so that we can track it.  It caused a regression, so we have backed it out.  I'm not sure how to solve for both cases right now, so I'm going to consider this a low priority issue for now.

**Comment by vincode-io** [comment]
I haven't forgotten this one and have spent way more time on it than I would like.  I still can't find a solution for it yet.

The issue is only occurs when the large title for Feeds is visible.  When the view transitions to having the small title in the bar, the problem doesn't exist.  It seems to be an intended animation so that the back button word "Feeds" can transition into the large title "Feeds".  I just can't figure out why the timeline navigationbar goes completely transparent instead of translucent.
