### ISSUE TITLE
Retention of read items

### ISSUE THREAD

**Issue by DutchPete** [Ranchero-Software/NetNewsWire#1325]
How many items are kept before the next new one pushes out the oldest? Or, is there a particular time an item is kept before it is deleted by the app?

I have not found a setting for this.

**Comment by brentsimmons** [comment]
Articles last for approximately three months after their arrival date (the date NetNewsWire first saw the article).

**Comment by DutchPete** [comment]
Wow, that's a long time. Is there any way I can shorten that, or remove some of the old articles manually?

**Comment by brentsimmons** [comment]
There isn’t. We will consider the ability to delete articles for a future release.

**Comment by Wevah** [comment]
Reeder has a preference for how long to keep read articles; perhaps we could do something like that.

**Comment by tubedogg** [comment]
To clarify, is this just read items, as the title states, or all items, as Brent's first reply seems to imply? In my case I have several Feedbin email -> RSS feeds that have about a hundred unread items dating to October/November in Feedbin, but right now only show about 60 items since about January 1 in NNW, so it seems like it applies to unread, as well.

I request that when/if this is being addressed to potentially shorten the time frame, it be able to extend the time frame, too, optimally on a per-feed basis, even if it's only for unread items.

**Comment by vincode-io** [comment]
The retention policy depends on the type of Account you have.  In your case, the missing ones from Feedbin are due to a known bug that has been resolved.  We should match Feedbin one-for-one on unread items.

@brentsimmons Could we change `fetchArticleIDsForStatusesWithoutArticlesNewerThan` to just be `fetchArticleIDsForStatusesWithoutArticles` so that the missing unread items come back for users hit by this bug?  We want to find all the missing articles regardless of when they arrived when the Account is a syncing service.  Since syncing services are the only consumers of this function, it should be safe to remove the dateArrived constraint.

**Comment by vincode-io** [comment]
Related to #1846.  I'm moving this to the 5.0.1 milestone so that we can close this issue with #1846.

**Comment by brentsimmons** [comment]
Closing this because it’s the same work as #1846.
