### ISSUE TITLE
Account: fetchArticleIDsForStatusesWithoutArticles() should be replaced

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1416]
We have orphaned statuses by design. We keep statuses for a very long time (the statuses table is only about 1-2% of database size).

But we want to keep articles only for NetNewsWire’s 90-day window. (Or the syncing service’s window, which may be different.)

Also: the replacement should be async. The current method is sync.

**Comment by vincode-io** [comment]
This is a poorly named function. It really returns any unread or starred article ID's where there isn't an article.  We need to retrieve the articles for those article ID's from the sync service so that we will match the sync service unread and starred articles which may be outside NetNewsWire's 90 day window.

**Comment by vincode-io** [comment]
I think the name originally worked, but a I updated the query, but not the function name.

**Comment by vincode-io** [comment]
This was renamed and resolved.
