### ISSUE TITLE
iPad: don’t animate selection highlighting when not navigating

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1439]
For instance: if I have an article selected in the timeline, and hit the down arrow, the next article is selected. The bug is that the highlight color fades out for the previous article and fades in for the newly-selected article — it should just be instantaneous in this case (no fading).

**Comment by vincode-io** [comment]
Removing animation from the selections also removes the scrolling animation when you reach the bottom of the table view.  This is because they are the same `UITableView.selectRow` function.

I can split this up into two separate calls to `selectRow`, to try to animate the scroll, but not the selection, but this complicates the code more than you might think.  That is because throughout the NNW iOS code, there is only one `animate` parameter on the functions.  `animate` typically denotes if a user is interacting with the system (it is true) or we are automating system functions (it is false) for things like state restoration, notification handling, etc...  It has no concept of partially animating the UI which would have to be added.

I prefer having the select animation and certainly want the scrolling animation.  Knowing now that this is going to get ugly in the coding, is this something you still want to implement?

**Comment by brentsimmons** [comment]
I’ll have to think about it. Is there a place in the code where I can toggle off the animations, so that I can see what the selection looks like un-animated?

**Comment by vincode-io** [comment]
You could shut it off by changing `UITableView.selectRowAndScrollIfNotVisible` in `RSCore` to always use `false` for the animated parameters.
