### ISSUE TITLE
iOS: Deleting/removing feed from Feedly doesn’t work

### ISSUE THREAD

**Issue by georgesnow** [Ranchero-Software/NetNewsWire#1470]
1. Manually add a feed
2. Uncategorized Feedly feed.
3. Swipe left tap delete or swipe to delete
4. feed deletes
5. Manually or next sync delete feed reappears

Didn’t see another report of this.

**Comment by vincode-io** [comment]
I ran into this too.  It seems to be a bug specifically when the Feed is in the Uncategorized folder.

**Comment by georgesnow** [comment]
Ok I was wondering that. I didn’t get a chance to try it with different category

**Comment by kielgillard** [comment]
I'm not sure it's a bug on the Feedly end. If anything, NNW should prevent users from deleting feeds in that category because Feedly treats it like a smart folder (the [documentation](https://developer.feedly.com/v3/categories/) calls it a "system category").

**Comment by vincode-io** [comment]
We have a similar problem on Feedbin.  They have a "Smart Feed" called "Pages" that shouldn't be allowed to be deleted.  We need some flag on sync system "Smart Feeds" and "Smart Folders" that tells the UI that deleting and maybe renaming isn't allowed.  Maybe it should be more fine grained and be a "deletable" flag on Feeds and Folders.

The question is do we want to tackle this in the scope of the iOS release or wait until a future release?  We could throw errors in the delegates when a user tries to delete a "Smart Feed" or a Feed in a "Smart Folder" instead of putting it in the UI code.

**Comment by brentsimmons** [comment]
We should tackle this in the iOS release. Objects in the Feeds list need some kind of property saying whether or not the user can delete them, and we should check that flag where needed.

**Comment by vincode-io** [comment]
@kielgillard Did one of your latest changes fix this? I thought I may have seen something about it in a pull request.

**Comment by kielgillard** [comment]
@georgesnow The latest TestFlight release is build 28. It fixed an issue _adding_ feeds to the uncategorized feed. Using the steps above, I could remove a feed from the Uncategorized folder using the swipe to delete action and the feed would not restore itself upon next or manual sync.

Is this still an issue for you? Or did I misunderstand something?

**Comment by georgesnow** [comment]
@kielgillard ok Yes this fixed the issue above with Url that is a valid a RSS feed.  Just as an  additional note  I discovered there is bit more to this bug. I actually added (By accident) a URL that was **not** an RSS feed. And that’s how I discovered the bug. I had tried deleting it and I couldn’t. This part still persists. I had to unfollow the feed from Feedlys iOS to remove it.

**Comment by vincode-io** [comment]
I've verified that this has been resolved in Build 28, so I'm closing this issue.
