### ISSUE TITLE
iPad:  Scroll position changes after app switch

### ISSUE THREAD

**Issue by johnwort** [Ranchero-Software/NetNewsWire#1494]
Repo steps:
1) select a long enough feed item to scroll.
2) scroll to the bottom
3) app switch by pulling up the dock and selecting a different app
4) app switch back to NNW

Result: The view is now offset “up” from the bottom position it was left at. 
Expected: the view scroll position to be where it was left, at the bottom.

Additionally I’ve noticed the offset can go in the other direction. My test for that was to open a scrollable item, then scroll down just to cover the headline as an easy marker. Upon returning from app switch I find the viewport offset increased resulting in additional scrolling “down”.

**Comment by vincode-io** [comment]
This is resolved except for one scenario.  When in 3 column mode if you are scrolled to the bottom, the position will change when switching apps.

This is because iOS quickly cycles between orientations when going into the background to get screenshots that it uses to make switching back to the app look faster than it really is.  When that happens, it is the same thing as switching to portrait from landscape.  This will have a longer viewable content area and the content offset will change if the content is scrolled to the end (or close to it).  When switching back to landscape the content offset is now wrong.

I can't think of a clean fix for this yet.  I'm going to take a break from it and think about it some more.  In the meantime, the position usually won't adjust itself anymore when switching apps.

**Comment by brentsimmons** [comment]
We don’t need to fix that one literal edge case for the 5.0 release, so I’ve changed the milestone.

**Comment by vincode-io** [comment]
Related: scroll position is lost if the feed has always show reader view enabled.

**Comment by vincode-io** [comment]
Ok, this guy is licked.  It will be in the upcoming 5.0.1 release.
