### ISSUE TITLE
iOS: Pull to refresh doesn't work in feed lists 

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#1520]
I tried to pull to refresh in the "All Unread" smart feed to see what's new but it unexpectedly did not work.  I think it should.

It does, of course, work in the top-level feeds screen, as expected.

**Comment by vincode-io** [comment]
This is by design. Because there is no visual feedback on the timeline to let you know if the pull to refresh would be successful or not, we don’t allow pull to refresh.

**Comment by blackketter** [comment]
Thanks for the response, @vincode-io !  Alas, I'm a little confused by it. 

Are you saying that it's a bad idea to support pull-to-refresh in list views?  Or just that there isn't a way to indicate progress?  

I don't quite understand how the top-level list of lists is different than the next level down list of items are different in this respect.

Maybe I should have marked this as a "feature request" that there be a way to refresh lists of articles...

**Comment by vincode-io** [comment]
The Feeds list has a progress indicator that begins to animate when you have successfully done a pull to refresh. This is how the user knows that the pull to refresh worked. 

You always need to give some kind of feedback to the user that the action they performed worked or not. If you don’t they will begin to distrust that the app is working correctly. 

Since we don’t have room for another progress indicator on the Timeline, we don’t have a pull to refresh.  It’s not that we don’t want to do the work of implementing it. It’s just that design sometimes means compromises.

**Comment by vincode-io** [comment]
We’re going to try something to make this work design wise. Reopening the ticket while we prototype some solutions.

**Comment by blackketter** [comment]
Great, thanks for the further consideration.

FWIW, here's a screen recording of my previous RSS reader, Byline, using the revealed spinner to show that an update is happening in the background.  It doesn't show progress, per se, but shows that the activity is happening.  Maybe this can provide some inspiration...

[RPReplay_Final1578006162.mp4.zip](https://github.com/brentsimmons/NetNewsWire/files/4017678/RPReplay_Final1578006162.mp4.zip)

**Comment by kielgillard** [comment]
I saw Message's "sending" progress bar on the bottom of the navigation bar and wondered if something subtle like that could be used to indicate sync progress on the timeline. I'd think it might not be since it seems to have acquired a sending semantic from Messages and Mail and NNW is not sending anything. On the other hand, Safari has it, and it's for both sending and receiving.

**Comment by vincode-io** [comment]
@kielgillard We used to have that style status indicator, but wasn't well received.  The current progress indicator is its successor.

**Comment by blackketter** [comment]
I see.  Could the existing Feeds list  progress indicator be used on other list pages by temporarily replacing the "Mark All as Read" button while refreshing?  During a refresh that button's behavior would be unpredictable anyway.

**Comment by kielgillard** [comment]
> @kielgillard We used to have that style status indicator, but wasn't well received. The current progress indicator is its successor.

Oh yes, I remember that now. But that was for the number of articles read, right, not the refresh progress on the timeline?

**Comment by vincode-io** [comment]
Nope, it was sync refresh progress on the timeline.  It only showed up on the phone tho.

**Comment by kielgillard** [comment]
But wasn't the controversy with respect to the progress bar showing in the article?
https://netnewswire.slack.com/archives/CPNED2D7Y/p1571789242168500

If it was in the timeline only, that might be ok?

**Comment by vincode-io** [comment]
Initially yes, but the conversation eventually progressed beyond that into some not understanding what the progress bar was for. We eventually settled into the design we have today, which I have to admit, is much better.

**Comment by vincode-io** [comment]
We've added pull to refresh and the progress indicator to the timeline.  Look for this in the upcoming release.

**Comment by blackketter** [comment]
Works great so far!
