### ISSUE TITLE
iOS: Change “Dismiss” in alerts to something more appropriate

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1580]
Often OK is the best thing. We should go through and check each of these and come up with the best button name in each case.

**Comment by vincode-io** [comment]
We have a common alert dialog that has "Dismiss" for the button, but I think that is it.  What is the button name we should use to dismiss an error dialog?

**Comment by vincode-io** [comment]
There is just one general error dialog and this is used for network errors.  Since there isn't usually anything we can do for the user to recover from these, the dismiss button now says "OK".  The Feedbin errors that we expect the user to recover by changing their credentials, now has an option to open the credentials.

I really think that is everything unless you want to assign different dismiss button values based on the network error itself.  Let's create a separate issue for that if you want to go that route.
