### ISSUE TITLE
iOS: Option to swipe right anywhere on an article to go back to the article list

### ISSUE THREAD

**Issue by psculthorpe** [Ranchero-Software/NetNewsWire#1596]
I love how 'native' NNW feels in general and wouldn't want it to stray from that too much, but I super miss (from Unread) being able to swipe anywhere in an article to go back to the article list.

Now that articles support swiping anywhere to navigate between them, would it be possible to also have an option to swipe right anywhere on an article to get back to the article list?

**Comment by myurieff** [comment]
I just installed the latest TestFlight beta and it is working as expected? If you do the gesture from the left edge, it goes back.

**Comment by psculthorpe** [comment]
I am suggesting an option to be able to swipe from anywhere on the article, rather than only from the left edge.

**Comment by vincode-io** [comment]
I’m sorry you are having problems. Muscle memory can be a pain to retrain. Unfortunately we don’t have any plans to make gestures configurable at this time.

**Comment by chaucerbao** [comment]
Even though there aren't any plans for this right now, I also want to throw my vote in for this feature.

I tend to have a lot of articles to go through, so my main view is the listing, where I tap into an article I'm interested in, then return to the listing page when I'm done. I rarely want to navigate from one article to the next, because that would take too long.

I know you can swipe from the left **edge** of an article to return to the listing. However, since I repeat this gesture many times, reaching across the screen to do a full swipe each time is noticeably tiring.

@vincode-io
