### ISSUE TITLE
Article view sometimes doesn’t fully update when moving to next article

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#1707]
We have a number of these, on both iPhone and iPad.

![Screen Shot 2020-01-25 at 6 57 41 PM](https://user-images.githubusercontent.com/1297121/73129974-b7db2400-3fa4-11ea-8d67-04ffaf89a8cb.png)

**Comment by brentsimmons** [comment]
Another screenshot. Note incorrect feed icon for Daring Fireball.

![screenshot_01](https://user-images.githubusercontent.com/1297121/73130015-86af2380-3fa5-11ea-9e45-265692735445.jpg)

**Comment by vincode-io** [comment]
These are probably two separate issues.

**Comment by pungerfreak** [comment]
Based on the response with commit 4a63b28, I suspect you believe the issue is timing. I have what, I at first thought, seems to be a similar occurrence. I didn’t want to incur another issue so I am posing it here first. In my case, however, it is a previous article that continues to appear when I view an unread item in any feed. It’s only on the first view. For example, I select a feed, then select a new article, I see the recurring article, I return to the feed and select another new article and I see the article I selected. It started in my Feedly sync but I was able to reproduce it in a feed from the default “On My iPhone” group. It’s not consistent, but it’s not infrequent, and it seems to have just started happening today. I’m on build 29 and I see build 30 is out. I’ll update to that and keep an eye out for recurrences. I’m not sure what else to include, so I’ll leave it at this. 

I have a screen recording but I’m unable to attach it from my phone. I’ll post this and update it later when I am at a computer and can provide the recording.

**Comment by vincode-io** [comment]
@pungerfreak We should have a Build 31 coming out soon.  When it does, if you see your problem again, please open a new issue for it.  I've done a bit of work to improve article viewer integrity and hopefully we got your issue taken care of in the process.
