### ISSUE TITLE
iOS: improve colors management for pure white/black favicons

### ISSUE THREAD

**Issue by sergeykrasilnik** [Ranchero-Software/NetNewsWire#1731]
![9B8447C6-81DC-4C85-8897-4C53F927C75B](https://user-images.githubusercontent.com/45911681/73332127-7aa9b700-426e-11ea-88f0-e55ec5f6a226.jpeg)

**Comment by vincode-io** [comment]
@sergeykrasilnik Could you do me a favor and supply that feed link for the pure white icon you ran into?

**Comment by vincode-io** [comment]
We will want to assign this to Mac 5.1 when it is fixed for iOS 5.0.1.

**Comment by sergeykrasilnik** [comment]
http://feeds.feedburner.com/dcurtis

**Comment by flowinho** [comment]
Suggestion: 

count color distribution in a fav-icon and when _all_ values are close to white (nut pure white because very subtle greys will also be hard to see) we draw a 50% Grey (because that’s the standard for neutral colors) around it - but only in “light mode”, not in dark mode.

The same thing should be happening for almost pure black Favicons when the app is in Darkmode.

**Comment by vincode-io** [comment]
We do this already for dark mode. We just need to do it for light mode too.

**Comment by flowinho** [comment]
Ah! Nice! Where can I find the reference?

**Comment by vincode-io** [comment]
https://github.com/Ranchero-Software/NetNewsWire/blob/master/Shared/Extensions/IconImage.swift

**Comment by flowinho** [comment]
Perfect, I can work with that.

**Comment by flowinho** [comment]
Feeds to test pure black icons (to verify that old functionality is still working):
https://500ish.com/feed

**Comment by sergeykrasilnik** [comment]
How about severe cases like this http://cherenkevich.com/feed/ pure black square icon that fills all the space?)

**Comment by flowinho** [comment]
@sergeykrasilnik That's really an almost impossible edgewise. Either we zoom the icon and display it, or we do nothing at all. The issue here at hand is how colours work: If we find out that the overall image is pure black, this does not mean we know it's _content_. A PNG with black pixels and some transparent background would still evaluate as _pure black_ but should nevertheless gain some background color. We _could_ examine the content of the feed-icon but that's a lot of engineering for a massive edge-cases of someone choosing a black square that fills all pixels as his feed icon.

**Comment by sergeykrasilnik** [comment]
I understand that and also that this is almost a single case problem but still an interesting design task)

![36D81341-E10F-4151-86F2-3E60F1BDFF2D](https://user-images.githubusercontent.com/45911681/76630361-8fa18780-6548-11ea-9c5c-f559097f12dc.jpeg)

Interesting that Reeder on top of adding extra white space also applies some kind of filter or something for dark icons so they aren’t pure dark.

**Comment by flowinho** [comment]
That would mean messing with the icon of the original feed owner. I mean, that's totally possible but... I don't like it. It's not my decision, everything design-wise is the territory of @brentsimmons but I'd say we shouldn't do it.

**Comment by sergeykrasilnik** [comment]
Totally agree. Messing with colors not cool. Just an observation about Reeder.

**Comment by vincode-io** [comment]
I'm assigning this to Brent to determine if we need to do this for the Mac.  Since we don't use pure black or white on the Mac, it might not be necessary.

**Comment by flowinho** [comment]
But it was already in place for pure black icons on the Mac. At least there was code.

**Comment by vincode-io** [comment]
It wasn't integrated with the Mac app yet.

**Comment by flowinho** [comment]
Ah okay.

**Comment by vincode-io** [comment]
I was mistaken, we do use pure white on the Mac for the timeline.  I'm going to go ahead and reassign to myself to implement it.
