### ISSUE TITLE
iOS feature request: Option to move Mark all as read on right side

### ISSUE THREAD

**Issue by leebutler** [Ranchero-Software/NetNewsWire#1749]
As a right hand dominant user I would like an option to put Mark all as read on the right side of the screen.

**Comment by vincode-io** [comment]
This is a tough one.  We like to be able accommodate as many requests as possible.  

The problem is that we don't want to make the user interface too fiddly.  The other problem is having too many configuration options.  This is the whole paradox of choice thing.  Presenting too many options can cause people to shutdown and not make any at all.

I'm sorry, but we're probably not going to do this one.

**Comment by irodknocker1** [comment]
Pity. 
As i already wrote on Slack, it can be very unusual to have the “Mark as read”-button on the left site and it can be very unhandy when you have a large display.

I guess this feature request isn't on of these "too many options". It's a very usefull request.
Especially there RSS clients out their with such an option.
![img_3395](https://user-images.githubusercontent.com/61420503/75161362-f2f38300-571b-11ea-976d-19dbca0c9005.jpeg)


Please conside it again.
