### ISSUE TITLE
iOS: Favicons and Icons fail to retry downloading if they experience a network error

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1791]
I've had a spotty cellular data connection lately.  One thing I noticed is that if a favicon or icon fails to download that they get added to the cache file that specifies that there isn't a favicon or icon.  In my case it was just a network timeout, so we should no be adding them to the cache so that they get retried again.

**Comment by Wevah** [comment]
I wouldn't be surprised if the same happens on Mac. Does the feed's homepage specify any favicons in the HTML, or does it just have a fallback `favicon.ico`?

**Comment by Wevah** [comment]
It looks like right now we don't disambiguate between "no favicon loaded because it doesn't exist" and "no favicon loaded because the connection failed".

**Comment by Wevah** [comment]
Confirmed that this also affects macOS, and isn't just confined to feed sites with just the fallback favicon.

**Comment by Wevah** [comment]
Aha: Looks like `currentHomePageHasOnlyFaviconICO` is never being set to `false` after it's `true` once if the fetch of the home page fails.

**Comment by Wevah** [comment]
The array of feed icons was still being set to the fallback `favicon.ico` even when `FaviconURLFinder` got `nil` metadata due to the page not loading. The fix is to fire off the callback with `nil` when the found URL array is already `nil` (it's the empty array if the metadata exists but contains no favicons).
