### ISSUE TITLE
iOS: picture only micro.blog items could be better formatted in the timeline

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1807]
![image](https://user-images.githubusercontent.com/16448027/75085602-c2bfa080-54df-11ea-8321-609c2b097f83.jpeg)

**Comment by flowinho** [comment]
You add “New picture post” or “New picture post by <author>”.

**Comment by alexcfaber** [comment]
Or have a different cell type which displays the image if there is only an image? Although there would be many edge cases I guess. What if there's only a video. 

What currently happens with other feeds when there is no title? Does NNW display the first sentence of the content? In that case 'New post by <feedname>' might be better?

**Comment by flowinho** [comment]
Regarding the very nature of RSS elements one could expect there are always the following properties:

- an image
- a title
- a summary / description

If NNW aims to consistently display feed objects that are missing either of these properties then there is imho no way around a placeholder for the title. A missing description can be hidden, a missing image could either be a placeholder or not being displayed at all, although that would interrupt the "flow" of information on the scrollable table view.

Hence why I suggested the generic title.

**Comment by thatguygriff** [comment]
When I submitted this screenshot in the Testflight build I wasn't necessarily thinking that there should be placeholder text, I think it is fine with no text. 

My concern was more that the blog name and timestamp end up aligning with the top of the cell (instead of the bottom of the cell on all other feed entries) and that the cell height is shortened so that it doesn't match the height of all other feed entries.

**Comment by flowinho** [comment]
Yeah it's because without a title the other UI elements do not know how to properly position themselves.

**Comment by flowinho** [comment]
I found a good feed to showcase the issue: https://micro.blog/kevinwhalen
