### ISSUE TITLE
iOS: articles should clear immediately from timeline on pull to refresh (when enabled)

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1834]

**Comment by cparnot** [comment]
Since that request was based on a comment I made for the equivalent macOS feature (see https://github.com/Ranchero-Software/NetNewsWire/issues/130), I figured I'd explain the rationale for the behavior, which might not be clear just from the issue title.

I think it would be better to have the articles disappear right away when refresh manually (and the option is on). The reason why one would choose this option (like me!), is to have a way to quickly dismiss read articles from the view. The refresh becomes a side effect of it (and a welcomed one), and will simply happen after that.

**Comment by vincode-io** [comment]
The application of this filter should also be applied to all windows, not just the one that received the refresh command.
