### ISSUE TITLE
Feed and Article Read Filter menu items need keyboard shortcuts

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#1842]

**Comment by vincode-io** [comment]
Assigning to Brent since this is his domain.

**Comment by vincode-io** [comment]
Changing milestone to iOS 5.0.1 since that is really the first place that these keyboard shortcuts should appear.

**Comment by vincode-io** [comment]
@brentsimmons, please reassign back to me once you design the keyboard shortcuts.

**Comment by brentsimmons** [comment]
![Screen Shot 2020-03-21 at 6 40 36 PM](https://user-images.githubusercontent.com/1297121/77240499-944ae900-6ba3-11ea-89fe-5ca51fd69562.png)

I changed the Clean Up command to Clean Up Articles, and gave it cmd-' — because that’s an easy shortcut to hit, and people who use this command will probably use it often.

Hide/Show Read Articles is now shift-cmd-H, and Hide/Show Read Feeds is now shift-cmd-F.
