### ISSUE TITLE
Feature Request: A settings toggle to enable feed-refresh when app becomes visible

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1865]
I'd like to have to opportunity to enable feature that tells the app: "Please refresh all my feeds when I open the app from background."

**Comment by vincode-io** [comment]
Is this for the iOS app?  If so, we already do this if you haven’t had a successful background sync in the last 15 minutes.

**Comment by flowinho** [comment]
Yes it’s for iOS. I understand the background refresh but I’d like to have the app refresh automatically every time it enters the foreground. 

It’s just a request, I don’t know (yet) if it aligns with UX you like to implement in NNW.

**Comment by vincode-io** [comment]
We don't do it every single time that you come back into the foreground because you might be bouncing between NNW and another app trying to do something.  We don't want to pummel the sync service every few seconds, which is why we only allow it every 15 minutes.

See this code for reference:  https://github.com/Ranchero-Software/NetNewsWire/blob/45bae1cd58da29889a72d4d99f6146e7e44e2d58/iOS/AppDelegate.swift#L155

**Comment by flowinho** [comment]
Understood.
