### ISSUE TITLE
Feature Request: More customizations like font sizes and disabling favicons on timeline layout for a more simplistic look

### ISSUE THREAD

**Issue by longgiangp** [Ranchero-Software/NetNewsWire#1872]
So far i really like this app! In terms of simplicity, FeedMe (https://github.com/seazon/FeedMe) takes the cake (at least for me). I am using the "list" view with "summary" turned on. And that one is the main reason i still have my android around. 

Now to my request:
I need more visible content, so i would like to disable the favicons (I only want to see white on black and nothing else). Also the read / unread indicator takes precious space. I think having the font of the read item greyed out would be sufficent. The indicator could be smaller and move down just next to the name of the feed.

The settings in timeline layout should consist of:

+ Favicons - toggle Switch
+ Font - Size slider
+ Headlines - Number of lines slider
+ Summary (or: first few sentences of the article) - Toggle Switch
+ Summary - Number of lines slider

Although i am pretty happy with article layout, it should also have settings like:

+ Font sizes
- slider for headlines
- slider for paragraphs
+ Title picture - Toggle switch
... just to name a few

Keep up the good work!

**Comment by vincode-io** [comment]
Thanks for the suggestion.  It looks like you put a lot of thought into it.

One of the things that we strive to avoid on NetNewsWire is overwhelming the user with configuration options.  It is very doubtful that we ever make the timeline as customizable as you suggest for this reason.  In fact, the main reason that the timeline is customizable on iOS is because of accessibility.  Large dynamic type sizes made our standard timeline layout unusable at larger sizes without some customization available to the user.

That isn't to say none of your suggestions will never be implemented.  I could see us allowing the feed icon (favicon) to be hidden.  (I've added issue #1877 to track this)  We might also implement an article image preview to the timeline.  See #1551.

As for customizing the article view, you'll be happy to see that is on the roadmap.  See issue #19.

Since this issue is too big to implement on its own and we largely have other issues that overlap it, I'm going to close it.
