### ISSUE TITLE
NetNewsWire opens to a read article.

### ISSUE THREAD

**Issue by chalxee** [Ranchero-Software/NetNewsWire#1893]
This is probably related to IOS 13 (and even IOS13,4 beta5) and not to the app itself because I had the same problem with another RSS reader app, but maybe new IOS versions demanding different handling. IDK, I’m not developer, but this issue is annoying.

**Comment by flowinho** [comment]
Hey 👋 

Can you specify a bit more what exactly is going on? Is NNW opening for you when you click on a feed-url? 

Also can you mention exact iOS version you are using? iOS13.4 b5 is correct?

**Comment by chalxee** [comment]
Hello, I’m using IOS 13.4 beta 5, but the reason why I entered beta program is because I faced similar problems but with other apps including IOS email app on IOS 13.3.
Scenario:
I open NetNewsWire and start browsing feeds(I’m syncing with Feedly). I go back from article list to a feed list and close NetNewsWire. After some time, I open again NetNewsWire and it opens not in a feed list bit it opens the article I already read. This scenario happens about 20% to 30% times I open this app. 
I had same problem with FieryFeeds app and as I mentioned at the beginning of my message, I had similar problem with email app and exchange account on previous versions of IOS 13.3 and all 13.4 betas before latest which seems that fixed email issue.
Thanks for fast reply.
Yeah, thanks for a such amazing app. This little gem is pure haiku: small, fast and beautiful:-)

**Comment by vincode-io** [comment]
@chalxee Do you force quit your apps by sliding them off the top of the screen?

**Comment by chalxee** [comment]
Yes.

**Comment by chalxee** [comment]
And phone model is iphone 7

**Comment by vincode-io** [comment]
It is a common misconception that force quitting saves on phone resources, but it isn't true.  It actually takes iOS more resources to completely quit the app than to leave it in the background.  I know that it looks like the app is still running when you switch to another application, but it isn't.  iOS suspends the app so that it isn't using up resources.  Completely stopping and starting the app is more resource intensive than just letting it suspend into the background.

I think what is happening in your case is that the app, be it Fiery Feeds or NetNewsWire, isn't having a chance to get the last place it was saved when you force quit the app.

I could be wrong and it could be related to you running the latest Beta.  If you are willing to help us out, could you try not force quitting your apps and then see if this problem still exists?  If it keeps happening, I will try to start debugging with the iOS Beta to see if I can recreate the bug.

**Comment by chalxee** [comment]
Yes, I’ll be glad but it would need at least ad day or two to be certain. I didn’t think of that possibility to be frank, but when you mentioned it it looks possible. I will report here my findings.

**Comment by vincode-io** [comment]
We really appreciate it!

**Comment by chalxee** [comment]
I’ll be glad. Already testing and it behaves predictably. It opens at the exact same place where it was when I suspended it.

**Comment by chalxee** [comment]
I can confirm that suspending app works good. If I sispend app in feed list it always opens in feed list On next Start. If I suspend it in article lost it starts next time in this same article list. If I suspend it in specific article, it always opens in this same article.

**Comment by vincode-io** [comment]
Thanks @chalxee!  I'm glad to hear everything is working out for you now.
