### ISSUE TITLE
【macOS】Why not support to add Feedly accounts?

### ISSUE THREAD

**Issue by poisonoff** [Ranchero-Software/NetNewsWire#1939]
Feedly accounts are only supported on iOS app , would you support Feedly in the future?

**Comment by vincode-io** [comment]
It is coming in the next Mac release.  

https://ranchero.com/netnewswire/frequently-asked-questions

**Comment by noahmaranesi** [comment]
@vincode-io any idea when that update will be coming? NetNewsWire 5 has been out for 9 months and still no Feedly support on macOS...

**Comment by vincode-io** [comment]
@noahmaranesi All I can say is that we are working on it and consider getting it our highest priority, right after we get out the 5.0.4 bug fix release that has to be done.

**Comment by brentsimmons** [comment]
We’ve had the Feedly sync code for only two months, since the release of NetNewsWire 5.0 for iOS. We’re working as quickly as we can on bringing Feedly sync to the Mac. We wish we were done already, too!

But please do remember that this is a free app made by volunteers. And right now there’s a pandemic going on. (And I got laid off and had to look for a job.)

I am enormously proud of the team, and the team will continue to work hard to bring the features people need to the Mac and iOS apps. We also work very carefully, because we value doing these things well more than we value doing them quickly.

**Comment by noahmaranesi** [comment]
@vincode-io, @brentsimmons: Thanks for the update!
