### ISSUE TITLE
Text being truncated in macOS version

### ISSUE THREAD

**Issue by eeshwar1** [Ranchero-Software/NetNewsWire#1956]
The last word of this article is not being displayed.

https://www.loopinsight.com/2020/03/29/what-the-right-to-repair-movement-gets-wrong/ 

<img width="870" alt="Screen Shot 2020-03-29 at 10 30 30 AM" src="https://user-images.githubusercontent.com/1115336/77853183-5a33a580-71a8-11ea-81a3-f37d17decb74.png">

**Comment by vincode-io** [comment]
Loop Insight doesn't always full article text some times it truncates it so that you will visit their website.  In this case, only one word didn't make it.  You can see the link at the bottom that says "Read this on The Loop" which shows that NNW isn't truncating the article.

I'm sorry, but there isn't anything we can do about this.

**Comment by eeshwar1** [comment]
Thanks for the explanation.
