### ISSUE TITLE
Contributing to this app using SwiftUI

### ISSUE THREAD

**Issue by joshuablum** [Ranchero-Software/NetNewsWire#1974]
Hey there everyone 👋

I've been learning iOS development with Swift and SwiftUI for a while now and thought that I could contribute to this project. I should mention that **my knowledge with UIKit is close to zero**. From my short observation there is no usage of SwiftUI in the iOS app. Technically it is possible to use SwiftUI in UIKit by wrapping SwiftUI componetns into a `UIHostingController ` and the app already targets iOS 13 so that shouldn't be a problem.  
So my question is whether or not it is welcome to contribute using SwiftUI.

Cheers and stay safe!

**Comment by vincode-io** [comment]
Hey @joshuablum!  Thanks for your interest.  Please join us in our Slack #work channel.  That is where all the action for contributors happens at and the best way to discuss with us your options.

We have worked with SwiftUI in the past.  Check out the post that our project lead, @brentsimmons wrote.  https://inessential.com/2019/10/21/swiftui_is_still_the_future

I hope you join us in Slack.  In the meantime, I'm going to close this since it isn't really an issue.

**Comment by joshuablum** [comment]
Thank you for the quick answer @vincode-io and the link to Brent's blog which was really helpful indeed. I am sorry but I don't use anything besides GitHub/GitLab and email for communication for several reasons but I completely understand you doing everything through Slack.
