### ISSUE TITLE
Background refresh doesn’t clear read articles

### ISSUE THREAD

**Issue by ZacharyBennett** [Ranchero-Software/NetNewsWire#1989]
When the All Unread feed is refreshed in the background, the All Unread feed doesn’t clear read articles while “Refresh to Clear Read Articles” is on. 

This may be due to many a time when I come back into this view it’s been sitting in All Unread in the background, but if new articles are being retrieved in the background then the read articles should go as well I think.

**Comment by vincode-io** [comment]
The NNW team has discussed this at great length.  We understand that some users would like automatic read article removal, but honestly, it will probably never happen.  We will most likely always require some kind of manual action from the user so that they aren't getting surprised by having read articles removed.
