### ISSUE TITLE
iOS and macOS: potential favicon problem

### ISSUE THREAD

**Issue by yikojom115** [Ranchero-Software/NetNewsWire#2030]
I add the feed URL:

https://hackernoon.com/feed?ref=hackernoon.com

Everything works fine but the home page URL is added as:

http://github.com/dylang/node-rss

The problem with this is the favicon for Hacker Noon inside NNW – but not e.g. Feedly's web app, Reeder.app, which show the Hacker Noon logo – is a photograph of the guy who owns this GitHub page.

It seems small but it's a bit irritating, as NNW looks so nice and it appears a bit random. And again, other clients seem to show this favicon "correctly".

But again, I'm not saying there's no method behind this and NNW is doing anything wrong.

Thanks for all your work Brett

**Comment by vincode-io** [comment]
The feed is incorrect.  It shows its home page to be `http://github.com/dylang/node-rss`.  Since we use the feeds specified home page to download high res versions of their icons instead of just the favicon, we are picking up something different than other readers.

We probably won't change that approach to support one misconfigured feed.  Your best bet is to contact Hacker Noon and have them fix their feed.

![Screen Shot 2020-04-29 at 12 56 12 PM](https://user-images.githubusercontent.com/16448027/80629999-31a60200-8a19-11ea-9b77-ff92675e4045.png)
