### ISSUE TITLE
FeedWrangler: Support Smart Streams/Folders?

### ISSUE THREAD

**Issue by jbennett** [Ranchero-Software/NetNewsWire#2048]
FeedWrangler has smart streams which function almost like folders. If you create a stream with no search filter and a list of feeds from your account, it will only have articles from those feeds. Additionally you can add a search filter so that only matching articles from the list of feeds are included in the stream.

This doesn't quite match the idea from folders, it's closer to a Smart Feed like Today or Unread. Do we want to make FW streams map to NNW folders and just do the work of hiding the difference, add the ability for Accounts to contribute to Smart Feeds in some way, or just not support FW Steams?

**Comment by vincode-io** [comment]
I think we need a new concept in NNW to make FeedWrangler's Smart Streams work.  Mapping onto Folders won't work because FeedWrangler also filters based on search term for FeedWrangler Smart Streams.  We also can't just map Smart Streams onto a WebFeed.  When you mark an item as read in a Smart Stream, it is actually marked as read in its owning WebFeed.

I think we need a new concept in NNW to make these work.  For lack of a better name, I'd call these Meta Feeds.  They are Feeds about Feeds.  We would need a new table in Articles to support this.  It would be a table of pointers into articles owned by other WebFeeds.  It might be as simple as a metaFeedID and an articleID.

https://feedwrangler.net/developers/streams#stream_items

We would also have to support the Meta Feeds in our OPML file.  I'd recommend we use the actual URL that the service uses to display the thing for both the Feed URL and the Home Page URL.  That way we can open straight to the web version of the thing with our usual open home page commands.  For example a test stream I created was `https://feedwrangler.net/streams/74384`.

Feedbin has a similar concept called Saved Searches that could also be supported by Meta Feeds.  https://github.com/feedbin/feedbin-api/blob/master/content/saved-searches.md

I think Feedly Boards could be supported by this.  What do you think @kielgillard?

This looks like something that we should add before releasing Feed Wrangler support to the public.  Feed Wrangler doesn't support Folders or Tags in the same sense that Feedbin or Feedly do.  It just has Smart Streams and uses those as a substitute when you do an OPML import there.  Without support for Smart Streams all feeds are just going to be in the root folder.

**Comment by vincode-io** [comment]
I just checked Reeder and it looks like it has the concept that I described above.  It shows the "Meta Feeds" with a search magnifying glass icon next to them.

**Comment by jbennett** [comment]
I was assuming this would be a full feature. Right now FW sync just throws up an error if you try to add a folder etc. Would it be better to add a "no folders" behaviour to be able to not list an account in the set of options to handle this more gracefully? Or would that potentially confusing if they don't know its not supported?

I personally don't think we have to wait to have this before releasing Feed Wrangler support, I'm ok with not having folders and don't use much of the smart streams myself. I just asked on Twitter if David Smith is willing to share any numbers around usage of Smart Streams to make sure I'm not an outlier.

**Comment by vincode-io** [comment]
Yeah, we will need a new AccountBehavior to disallow Folder management.

**Comment by jbennett** [comment]
I'm happy to make an issue/assign it to myself if you like.

**Comment by vincode-io** [comment]
That works for me.

**Comment by kielgillard** [comment]
Feedly [Boards](https://developer.feedly.com/v3/boards/) (synonymous with Feedly tags) are more like a custom starred articles: an article has one or more tags and the stream for that tag is the set of articles the user curated.

I’m not sure there’s a matching concept in Feedly for saved searches that’s relevant for nnw. There might be priorities or a keyword alert feature but I think they can be modelled as folders.

**Comment by vincode-io** [comment]
FeedWrangler is shutting down so we don't have any further plans to support it.
