### ISSUE TITLE
Implement multiple selection in Sidebar

### ISSUE THREAD

**Issue by vincode-io** [Ranchero-Software/NetNewsWire#2164]
I can't find any native SwiftUI support for this right now.  I'm going to move forward with single selection for now, but we should implement this as it is a macOS feature currently.  Here is an article that may help implement this.  https://www.pawelmadej.com/post/multi-select-picker-for-swiftui/

**Comment by stuartbreckenridge** [comment]
I have multiple selection working to a point.

I added `@Published var selectedSidebarItem = Set<Int>()` to `SidebarModel`, then updated the `List` initialiser in `SidebarView` to include it `List(selection: $sidebarModel.selectedSidebarItem)`, then added tags to each of the sidebar items in the sidebar: either `.tag(sidebarItem.id.hashValue)` or `.tag(sidebarItem.feed!.feedID!.hashValue)`. With this, you can multi-select anything, top-level items, feeds, folders, feeds in folders.

The problem is that only the Smart Feeds and On My Mac top-level sidebar items are updating the `selectedSidebarItem` Set with new hash values. You can see both hash values for top-level items in the Set when both are selected, but it updates with nothing new when you select an actual feed.
