### ISSUE TITLE
iOS: position of first/next unread button is inconsistent

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#2208]
When viewing a feed, the “first unread” button is at the right side of the toolbar. However, when viewing a single article, the “next unread” button is in the middle of the toolbar. This is an inconsistent placement for a button with the same icon or similar function. Swapping the positions of the share and “next unread” buttons in the article screeen would allow tapping one spot to navigate through all articles in a feed.

<img src="https://user-images.githubusercontent.com/25517624/86514336-c3e2d180-bddf-11ea-835b-19965282b280.jpeg" height=100>

<img src="https://user-images.githubusercontent.com/25517624/86514340-cba27600-bddf-11ea-934f-ee15a30b5e51.jpeg" height=100>

Proposed:

<img src="https://user-images.githubusercontent.com/25517624/86514556-0eb11900-bde1-11ea-935a-3b6e6d1baad3.png" height=100>

**Comment by vincode-io** [comment]
The next unread button is in the middle on the Article view because it is the most used button and we wanted it to be easy to reach.  You make a good point about consistency, but the tradeoff is that it is more difficult to reach for some users.

We will revisit the toolbar icon placement for version 6 of NNW, but changing the placement now will mess up the muscle memory of users of the app today.
