### ISSUE TITLE
Performance issues on 5.0.4

### ISSUE THREAD

**Issue by sgoodwin** [Ranchero-Software/NetNewsWire#2325]
This last release seems to have made it worse, but when I first open the app, there's always a delay of at least 10 seconds before the list of articles is populated. Now with 5.0.4, it goes a step further and beachballs during that time. I'm on a 2018 MacBook Pro (2.2gz 6-core Intel i7) with 16GB of ram with at least 4GB free when I open the app.

**Comment by michaeljtsai** [comment]
Since updating to 5.0.4, I also am seeing a longer delay at launch, and once it got completely stuck with a beachball (sample attached).
[Sample of NetNewsWire.txt](https://github.com/Ranchero-Software/NetNewsWire/files/5048139/Sample.of.NetNewsWire.txt)

**Comment by brentsimmons** [comment]
@michaeljtsai Your sample is very, very strange. Do you have any idea what could cause runaway com.apple.network.boringssl.metrics_queue serial queues?

**Comment by brentsimmons** [comment]
@sgoodwin @michaeljtsai Are you using Feedbin syncing or On My Mac? Or both?

**Comment by brentsimmons** [comment]
What NetNewsWire messages are appearing in Console?

**Comment by michaeljtsai** [comment]
@brentsimmons I'm using Feedbin and On My Mac. Is it perhaps using one queue per feed? I have about 1,500 local feeds.

**Comment by brentsimmons** [comment]
@michaeljtsai If you disable the On My Mac account (you can turn it off in preferences, and turn it back on later), then re-launch, does this still happen?

**Comment by brentsimmons** [comment]
Another thing to try — turn off sharing Mac analytics, then re-launch NetNewsWire and see if it still happens.

Here’s where the pref is. (Turned on in this screenshot.)

![Screen Shot 2020-08-09 at 1 33 41 PM](https://user-images.githubusercontent.com/1297121/89741316-0afa5d00-da45-11ea-92e4-34c7622ae51b.png)

**Comment by michaeljtsai** [comment]
@brentsimmons I’ve always had the analytics off. If I disable the local accounts, it launches and refreshes almost instantly. With the local accounts, 5.0.3 takes about 56s to refresh, while 5.0.4 takes about 67s. It seemed like a bigger difference before I timed it because the progress bars behave differently. With 5.0.3, it moves very quickly up to about feed 1472 and then gradually finishes. With 5.0.4, it gets stuck for almost the entire time displaying a feed in the early 1300s and then instantly zooms to the end. This is not a big deal for me because I can still browse feeds and articles while it’s refreshing. I only posted here because of the beach ball hang (which hasn’t recurred) and because the release notes said that fetching was *faster,* which wasn’t what I was seeing.

**Comment by brentsimmons** [comment]
By “fetching” I meant fetching from the database. That should have been made more clear.

**Comment by brentsimmons** [comment]
I suspect the beachballing had to do with some new database cleanup code. The databases hadn’t really been kept clean, so with a large number of feeds it’s likely that this code took a while to do its thing the first few times.

The problem should go away, and refreshing-feeds performance should be pretty much the same as 5.0.3.

I’m going to close this. I’ll reopen it if it turns out to be a chronic issue.

**Comment by sgoodwin** [comment]
I'm using local-only feeds. Here's a screenshot of the logs because I couldn't remember how to save just the bits from NNW:

<img width="1298" alt="Screen Shot 2020-08-10 at 22 01 41" src="https://user-images.githubusercontent.com/30485/89825680-3cfae480-db55-11ea-8d0e-51b78e324f46.png">
