### ISSUE TITLE
Preferences > Accounts - On My Mac icon blurry in sidebar (non-retina screen)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2357]
![Screen Shot 2020-08-16 at 1 23 23 PM](https://user-images.githubusercontent.com/1297121/90343270-c0885b80-dfc3-11ea-8125-b8bb1e13493c.png)

**Comment by vincode-io** [comment]
I'm not sure how to fix this.  We use a common image for the account and that gets used in at least 3 different places with 3 sizes.  For example here it is at its largest.

<img width="624" alt="Screen Shot 2020-08-31 at 5 35 11 PM" src="https://user-images.githubusercontent.com/16448027/91775429-a304e580-ebb0-11ea-81ef-f952ab24cea3.png">

If I tune the image for a small size at 1x, it is going to look bad at the larger size.

We could do small, medium, and large sizes, but that would require the graphic to be created 3 different times since we can't just scale them without the image aliasing.  We would then need to do that for all account types.

**Comment by brentsimmons** [comment]
Let’s punt this one to the future

**Comment by brentsimmons** [comment]
Bugs on non-retina screens are increasingly hard to handle — I no longer have any non-retina screens.
