### ISSUE TITLE
Sidebar cell width incorrect at startup

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2385]
This is a weird one. I don’t know why it’s happening, and I haven’t been able to find a work-around, and I’m hoping Maurice will be able to figure it out.

![Screen Shot 2020-08-30 at 9 04 51 PM](https://user-images.githubusercontent.com/1297121/91681858-9925a880-eb04-11ea-8f2e-e959bd6c2e3b.png)

**Comment by vincode-io** [comment]
What is happening is that the table column isn't automatically resizing with the outline view.  This can happen if the table column width isn't set perfectly.  Right now I have it set to 3 pixels less than the containing scrollview.  This seems to work better.

I've been having trouble testing this.  It doesn't show up on my main development machine.  I assume that it is because it is running Big Sur.  My backup dev machine has that weird bug where it incorrectly is reporting the row width and so the unread count indicator is always positioned wrong.

If I still haven't got this thing fixed right, try tweaking the table column width to see how it behaves on your setup.
