### ISSUE TITLE
cmd-w should not close window if cmd-n doesn't just re-open window

### ISSUE THREAD

**Issue by slater** [Ranchero-Software/NetNewsWire#2477]
Right now, it's possible to close the main NNW window with cmd-w. I understand this is somewhat expected behavior via Apple HIG etc., but by the same token, cmd-n would re-open a window. Which it does, but also triggers the "add new feed" command at the same time.

Proposals:
1) Either get rid of cmd-w functionality entirely, or
2) If window is closed, hitting cmd-n should re-open the main window WITHOUT triggering the "add new feed" command.

**Comment by lorenzolewis** [comment]
Looking through other apps, this seems to be the same behavior. In Xcode for example, when you close all active windows, ⌘N will open a new file dialog, not the start screen for Xcode. To open back up the main window, the expected behavior is to click the dock icon again, search for the app to open it, or open it from Finder or Launchpad.

**Comment by vincode-io** [comment]
You can open a new window by pressing option-cmd-n without triggering the "add new feed" command.  cmd-w to close a widow is standard Mac behavior and not something we would want to change.
