### ISSUE TITLE
Debug menu unavailable

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#2491]
After enabling the debug menu (`defaults read com.ranchero.NetNewsWire-Evergreen ShowDebugMenu` outputs `1`), the debug menu remains hidden in the app. It’s visible at first but quickly hides itself before NetNewsWire finishes launching. I’m currently on the Test channel (Version 5.1.1 (3012)). How can I enable the debug menu?

**Comment by vincode-io** [comment]
Did you participate in the last NetNewsWire beta?  If so, you might have an app container laying around that your user defaults is giving higher precedence to than the unsandboxed one.

Delete `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen`

then run

`defaults write com.ranchero.NetNewsWire-Evergreen ShowDebugMenu 1`

and hopefully your problem is fixed.

**Comment by j-f1** [comment]
That was the issue! Removing the container let me enable the debug menu.
