### ISSUE TITLE
Articles disappear when moving feed to Feedbin

### ISSUE THREAD

**Issue by adrianburmester** [Ranchero-Software/NetNewsWire#2496]
I added a feed (blog.halide.cam) to "On my Mac", it fetched 10 Articles.
When moving the feed into a Feedbin-Folder, all but the newest article disappear.
They reappear if the feed is moved back.

In the Feedbin web interface, they all appear, even though only one is shown in NNW.

<img width="624" alt="MBP16 2020-10-15 um 18 39 05" src="https://user-images.githubusercontent.com/30344284/96162862-5a637a80-0f19-11eb-8927-f30f13058ed4.png">
<img width="1407" alt="MBP16 2020-10-15 um 18 41 39" src="https://user-images.githubusercontent.com/30344284/96162891-65b6a600-0f19-11eb-978b-ac49d785b8d4.png">

**Comment by vincode-io** [comment]
We only sync the last 90 days of articles for Feedbin and the other syncing services.  We do this so that we aren't syncing too much data and over taxing the syncing service.

The On My Mac account works differently and will sync any article still in the feed regardless of how old it is.  That is why you are seeing a different number of articles between the two accounts.

This is normal behavior, so I'm going to go ahead and close this issue.  Feel free to reply if you have any questions you would like answered.

**Comment by melgu** [comment]
On iOS the timespan seems to be 30 or 31 days, or am I mistaken?

**Comment by vincode-io** [comment]
iOS is 90 days as well.

**Comment by melgu** [comment]
I saw, that one can only switch read/unread on articles which are at most a month old, so I guessed those things were connected.

**Comment by vincode-io** [comment]
You should only have the read/unread marking restriction of 30 days on Feedly accounts.  Did you observe this on a Feedbin account?

**Comment by melgu** [comment]
Ah, no, on a Feedly account. Sorry for the confusion.
