### ISSUE TITLE
Adding Noodlesoft feeds fail because of certificate validation (maybe?) 

### ISSUE THREAD

**Issue by justin** [Ranchero-Software/NetNewsWire#2539]
### Steps to Reproduce

1. Open NetNewsWire Version 5.1.1 (3012) on macOS Catalina 10.15.7 (19H2)
2. File -> New Feed 
3. Enter any of the following values. 
    - https://www.noodlesoft.com/blog/
    - https://www.noodlesoft.com/blog/feed/
    - https://www.noodlesoft.com/blog/feed/atom/
    - https://www.noodlesoft.com/blog/feed/rss
4. The response back from NNW is "Can’t add a feed because no feed was found." 

If I open any of the feed URLs in the [w3c validator](http://validator.w3.org/feed/), the response is that the certificate validation failed. 

### Expected Results

Ideally the feed can be added, independent of the certificate result. But I understand why that may not be desirable. 

Alternatively, maybe a better error message can be returned than just the generic "Can't add feed" message?

**Comment by brentsimmons** [comment]
If we can’t read the feed due to a certificate issue, then that means we can’t actually _find_ it — since we can’t read it to know if it’s a feed. “No feed was found” is true!

But maybe we could detect that there was a certificate error and add something to the error message that it may have been due to a certificate error.

**Comment by justin** [comment]
. . . I don't even remember filing this.  🫠

The feeds seem to work now so closing it out.
