### ISSUE TITLE
Articles synced via FeedBin do not update in NNW when the published version is updated

### ISSUE THREAD

**Issue by DaveWoodCom** [Ranchero-Software/NetNewsWire#2549]
I have all of my feeds synced via FeedBin. NNW seems to grab the content of articles one time, and never updates them even if the source updates.

For example, this article on DaringFireball has a placeholder instead of a link: https://daringfireball.net/2020/11/disclosing_a_few_thoughts_on_facebooks_ui_design The article started as "I ran into [this piece at MacRumors] about Facebook", and then later the "[this piece at MacRumors]" part was changed to a valid link.

If I view the article in NNW, I still see the placeholder. If I log into FeedBin directly, it has updated correctly. There seems to be no way to even force a refresh in NNW for it to pull the latest, correct version.

I have seen this for a while, and in some cases, gone back to the article in NNW a week or so later and it still has the old information, never seeing content changes when an article has been updated.

Current version of NNW: Version 5.1.2 (3016) (macOS). This report is for the macOS version of NNW, however I believe it's also an issue with the iOS version (just not 100% sure right now).

**Comment by vincode-io** [comment]
@benubois Currently we are doing the following to get new and updated article content:

`https://api.feedbin.com/v2/entries.json?since=2020-11-04T21:09:07.000000Z&per_page=100&mode=extended`

I did some debugging and I don't think we are getting updated articles with the `since` parameter.  Only new ones.  Am I wrong or do I need to do something else to get the updated articles?

**Comment by benubois** [comment]
Hi @vincode-io,

The `since` parameter refers to entries _published_ since the value.

Most article corrections occur pretty quickly, so one change you could make is to backdate `since` to something like `last_sync_date - 1.day`.

There's also the [Updated Entries](https://github.com/feedbin/feedbin-api/blob/master/content/updated-entries.md) API. This can give you IDs of articles with _significant_ changes to the content. This one also supports a `since` parameter that refers to the `updated` date.

For example here is an article that had follow-up content added to it later. Feedbin has a special section for these to call attention to the fact that significant content has been added.

<img width="1084" alt="Screen Shot 2020-11-05 at 1 10 15 PM" src="https://user-images.githubusercontent.com/133809/98239520-5fd84180-1f68-11eb-9ace-4a30a3013543.png">

**Comment by vincode-io** [comment]
@DaveWoodCom We've made a change that will pick up any edits made within 24 hours of the original post being made.  This is the best compromise we make with regards to syncing performance and getting the edits.  These edits may take up to 24 hours to appear, but you can force them to appear by restarting NetNewsWire and doing a Feedbin sync.

This change will be coming in NetNewsWire 6.0.

**Comment by DaveWoodCom** [comment]
Thanks. That sounds like a good solution given the way the API works.
