### ISSUE TITLE
Article view is missing separator below toolbar when contents is scrolled

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2633]
Sidebar and timeline have the separator, but the article view doesn’t.

<img width="1347" alt="Screen Shot 2020-12-05 at 4 32 55 PM" src="https://user-images.githubusercontent.com/1297121/101268440-a069dd00-3717-11eb-826c-59ff9bf54dfd.png">

**Comment by vincode-io** [comment]
This is almost assuredly a AppKit bug.  Here is a screenshot from a bare bones project that does nothing special that demonstrates the visual artifact.

<img width="1076" alt="Screen Shot 2020-12-06 at 12 08 54 PM" src="https://user-images.githubusercontent.com/16448027/101288439-25a6cd80-37bc-11eb-939b-8a310f57b8a0.png">

From my experimenting this is because the toolbar isn't able to track the scrolling of the web views.  Moving the location in the split view of the web view moves the visual artifact with it.  This is probably why it works well in Mail, but not in NetNewsWire.

I've filed a FB for this bug.  FB8930675

We can set the Toolbar to always show the separator if we want.  We will lose out on the cool unified thing for when the content isn't scrolled, but it will look more consistent.

We could try adding the separator ourselves by observing the enclosing NSScrollView for the WKWebView.  I'm not sure we can get it to work.  We might run into the same problems observing the NSScrollView that Apple did.  Besides, if they fix the bug we might have a new visual artifact from us simulating it alongside it working.

**Comment by brentsimmons** [comment]
Got it. Moving this to the Future milestone and hoping Apple fixes it.

**Comment by brentsimmons** [comment]
This appears to have been fixed in later macOS versions.
