### ISSUE TITLE
iCloud missed syncing one feed

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2654]
My laptop has one more feed than does my desktop. (I’ve given it more than 24 hours.)

When I added that my own blog as the very first, I got some kind of error reported, but the feed actually got added.

However, it doesn’t seem to sync across.

Laptop:

<img width="181" alt="Screen Shot 2020-12-07 at 10 08 33 PM" src="https://user-images.githubusercontent.com/1297121/101447029-3f8a0280-38d9-11eb-8412-d6a82ff7ceb9.png">

Desktop:

![Screen Shot 2020-12-07 at 10 09 04 PM](https://user-images.githubusercontent.com/1297121/101447040-4749a700-38d9-11eb-85c3-d4f9b053d024.png)

**Comment by brentsimmons** [comment]
Desktop iCloud folder: 
[2_iCloud.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5657210/2_iCloud.zip)

**Comment by brentsimmons** [comment]
Laptop iCloud folder:

[2_iCloud.zip](https://github.com/Ranchero-Software/NetNewsWire/files/5657224/2_iCloud.zip)

**Comment by vincode-io** [comment]
Giving it some time won't bring that into sync.  Is it possible to delete the extra feed and add it again?

I'm assuming you don't remember the error you got?  It shouldn't add the feed locally if there was some kind of iCloud error encountered, but that is what looks like happened.

**Comment by brentsimmons** [comment]
I don’t remember the error. I should have taken a screenshot, and I missed it.

**Comment by brentsimmons** [comment]
Never mind — I do remember. It was generic, though: “An unexpected CloudKit error occurred.”

**Comment by vincode-io** [comment]
I'll go back over the Feed adding code again and see how you got the local feed created if a CloudKit error occurred.  That shouldn't have happened.

**Comment by brentsimmons** [comment]
I deleted it from my laptop, and got “An unexpected CloudKit error occurred.” — but it did delete.

Then I went to re-add it, and the app told me it couldn’t add it because I was already subscribed. And then it re-appeared. The subscription still doesn’t appear on my desktop.

**Comment by vincode-io** [comment]
I think I've got this fixed.  Here's what happened.

I don't know why you got the iCloud error, but it happened and we should handle it gracefully.  Instead, we created a feed in the local database even though we got the error.  This won't happen anymore if you get an iCloud error.

Then we had a corrupted feed in the local database that didn't have enough information to try to delete the iCloud version of itself, because the iCloud version didn't exist.  I've changed the delete code to still not delete if we get an iCloud error, but it will delete if the error is due to a corrupted Feed.

So you should now be able to delete your corrupted inessential.com feed on your laptop and then if you add it again and there is an error, you won't get a corrupted version.
