### ISSUE TITLE
Feature Request: Option to not leave "All Unread" view after marking all as read

### ISSUE THREAD

**Issue by petebocken** [Ranchero-Software/NetNewsWire#2702]
Currently when tapping the Mark All as Read button, you are taken from the All Unread view back to the main Feeds view. This requires the repeated actions each time you use the app if you only use the "All Unread" view.

Open app, tap "All Unread", scroll through articles, mark all as read, go back to Feeds view, (close app possibly, come back later), pull to refresh to get new articles, tap "All Unread", rinse and repeat.

This is the same behavior as other apps like Reeder. I like the ease of staying on one screen and simply pulling to refresh the one screen to get new articles like the Feedly app.

I'm assuming after a designated timeout, the app would resort back to the main Feeds screen again, so being able to choose a default Smart Feed would be required as well.

Maybe I'm asking for too much, but I really do like a streamlined app that doesn't require so much taping and swiping back and forth just to read new articles.

**Comment by vincode-io** [comment]
I don't think you are asking too much.  Asking doesn't hurt.

The problem is that we can't have it both ways.  If we took that feature away from people, we would be getting complaints about the change.  We could put in an application preference for it, but too many of those confuse people, so we are very reluctant to do that.

We do know that some people like to just sit on the Unread Feed and not move off it.  We've added some features to facilitate that, like the option to clear Articles on refresh.  I just don't see how we can do this one and not get a lot of backlash.  My apologies.
