### ISSUE TITLE
iOS client not showing any items when syncing from Feedly - NNW 5.0.5 (Build 56)

### ISSUE THREAD

**Issue by ottumm** [Ranchero-Software/NetNewsWire#2710]
In my iOS app, all my folders exist as before, but every folder is empty (of both read and unread items). This just started today for me. I have one RSS account, syncing via Feedly.

My Mac NNW client, synced to the same Feedly account, shows items correctly.

I've tried disabling and enabling the Feedly account in the NNW iOS app, as well as restarting my phone. My next step is to try deleting and re-installing the app, but I wanted to see if there was diagnostic info I could upload here first.

**Comment by vincode-io** [comment]
That is unusual.  It sounds like your Articles database got corrupted or deleted or something.

Thanks for the offer of providing diagnostic information.  Unfortunately, I would like to see your Articles database and it is crazy difficult to extract from the iPhone.  If we see this again, I think we would want to do something more heroic.

For now, let's just try to get you back to normal.  Instead of deleting and reinstalling, let's just delete the Feedly account and add it again.  If that doesn't work, then try deleting and reinstalling.

Please let us know the outcome.

**Comment by kevinm6** [comment]
First, update to NNW 5.1.3 then try to sync the feeds.

**Comment by ottumm** [comment]
> First, update to NNW 5.1.3 then try to sync the feeds.

@kevinm6 I have my iPhone set to auto-update and it appears that 5.0.5 is the latest version of NetNewsWire on the app store. So, ?

**Comment by kevinm6** [comment]
Sorry, my mystake. You're right, I was thinking about macOS!

You can try to uninstall (not delete) the app on iOS. 
I have the same configuration but I never get into similar problem.

**Comment by ottumm** [comment]
> Instead of deleting and reinstalling, let's just delete the Feedly account and add it again.

@vincode-io this worked, thank you!

**Comment by vincode-io** [comment]
@ottumm I'm not sure what happened to your Articles database, but it looks like it compromised somehow.  Sorry about that.  We'll keep an eye open to see if this happens to anyone else.
