### ISSUE TITLE
Feedbin: after updating credentials due to a failed refresh, it should automatically refresh that account

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#2713]

**Comment by vincode-io** [comment]
Should we just make it so that we do a refresh after any credentials update on any account?  Maybe they cancelled out of the dialog, went to get their password, and came back in through the Settings path.  It is really difficult to determine the reason for the credentials change, so maybe we should just always do it.

**Comment by brentsimmons** [comment]
That makes sense — agreed.
