### ISSUE TITLE
macOS NNW 6.0a1: All articles unread after moving from "My Mac" to "iCloud" in Sidebar

### ISSUE THREAD

**Issue by wucas** [Ranchero-Software/NetNewsWire#2783]
Hi,

I just downloaded 6.0a1. After enabling iCloud sync in preferences I dragged my feeds from the "On My Mac" section in the sidebar to the iCloud section. That worked fine (although the first feed took a couple of seconds the ones after that moved immediately) but the unread counter was reset, i.e. when before no unread messages were shown (correctly) all messages were shown as unread.

**Comment by vincode-io** [comment]
This is intended behavior.  We don't have the ability to copy read status between accounts because of the complexity involved in doing so. Different sync services identify articles differently and there isn't any good way to match them up. We don't feel like we can implement this in a satisfactory way.
