### ISSUE TITLE
Invisible tables rendered with blue lines in reader view on 6.0a1

### ISSUE THREAD

**Issue by momenabdelkarim** [Ranchero-Software/NetNewsWire#2787]
### Unexpected behavior: 
NNW6 renders tables with a border thickness of 0 when it shouldn't. 

### More info:
There was a discussion about not rendering table borders with a thickness of 0 in the Slack (link to part of the conversation: https://netnewswire.slack.com/archives/CC4LQ2D8R/p1602196503109400). This change was successfully made in NNW 6.0 in the regular mode but it looks like it wasn't applied to the reader mode.

### Images:

The first image shows the article without reader view, the latter with it enabled.

<img width="628" alt="Screen Shot 2021-02-05 at 10 37 45 AM" src="https://user-images.githubusercontent.com/7445956/107068720-34026d00-679e-11eb-9d05-e1d0949c1d30.png">
<img width="635" alt="Screen Shot 2021-02-05 at 10 37 37 AM" src="https://user-images.githubusercontent.com/7445956/107068728-35cc3080-679e-11eb-88e6-480ea95c9796.png">

**Comment by vincode-io** [comment]
@momenabdelkarim Do you have the URL of this feed that you can give me?

**Comment by vincode-io** [comment]
@momenabdelkarim I can't recreate this if you don't give me a feed URL that you are seeing this bug on.

**Comment by momenabdelkarim** [comment]
Sorry got busy. It's a URL private to me (created by "kill the newsletter") so I can't post it publicly, but I shared it with you over Slack. Direct link to the DM: https://netnewswire.slack.com/archives/D01CF17CV5J/p1602189288000200

**Comment by vincode-io** [comment]
Thanks for the links. They are www.kill-the-newsletter.com links for the curious.

When you use reader view to retrieve the newsletter from Kill The Newsletter, our Mercury reader service strips out the outer most table that specifies `border=0`. Kill The Newsletter is also using `border-collapse` to make the formatting of the tables used in newsletters look nicer. Because we don't get the styles or the `border=0` from Mercury, we don't have any way of knowing that they intended to hide the borders.

**Comment by brentsimmons** [comment]
I don’t think this is a thing we can do anything about, so I’m closing it. Reopen it if I’m wrong.
