### ISSUE TITLE
Add Miniflux API support 

### ISSUE THREAD

**Issue by anyuzu99** [Ranchero-Software/NetNewsWire#2859]
https://miniflux.app/docs/api.html

**Comment by dumprop** [comment]
Look like duplicate #76

**Comment by sayomelu** [comment]
MIniflux API is different than the Fever API

**Comment by dumprop** [comment]
Why MIniflux API is better than Fever API?

**Comment by doamatto** [comment]
> Why MIniflux API is better than Fever API?

The main difference would be that the Miniflux API is still supported, where as (afaik) Fever is not. Based on how with Fever the devs favour services with their own APIs (mostly to reduce the capabilities of deployment errors), this may be a better suit than the Fever alternative. Ideally, both should be added; but, in the case of Miniflux, either or will work, the latter providing more support for other services (Fever, that is)

**Comment by doamatto** [comment]
I looked inside Miniflux earlier today and noticed that they (Miniflux) are currently working on adding Greader support (added to NNW in #766). When that merges, it may be the easiest way to integrate Miniflux in, apart from the official APIs.

**Comment by doamatto** [comment]
miniflux/v2#1115 was recently merged (woo!) meaning Greader support will be available in the next release and is currently available for those building from source using the `master` branch. Adding support soon in a similar fashion to FreshRSS would be the next and final step to bringing Miniflux to NNW, touch wood.

**Comment by boggydigital** [comment]
As @doamatto noted Google Reader API has landed and seems to be working great with NetNewsWire. For curious folks here is how to set it up:

- Go to your miniflux instance (let's say http://192.168.1.1:1234/ and open Settings, observe new Google Reader section
- Check Activate Google Reader API, add Username and Password and click Update
- Open NetNewsWire > Preferences... > Accounts > + > select FreshRSS under Self-hosted > Continue
- Set "Login:" to Username, "Password:" to Password you've used when activating Google Reader API in Miniflux, use you instance URL (e.g. http://192.168.1.1:1234/) as "API URL:", click Create
- You'll find yourself back in the Accounts dialog, feel free to add "Name" so that it shows nicely in the sidebar

You should be all set!

**Comment by schwantuschke** [comment]
If you don't need a port use the API URL: https://feeds.example.com
Without / at the end.

**Comment by vincode-io** [comment]
Duplicate of #76

**Comment by simpzan** [comment]
> As @doamatto noted Google Reader API has landed and seems to be working great with NetNewsWire. For curious folks here is how to set it up:
> 
> * Go to your miniflux instance (let's say http://192.168.1.1:1234/ and open `Settings`, observe new `Google Reader` section
> * Check `Activate Google Reader API`, add `Username` and `Password` and click `Update`
> * Open NetNewsWire > Preferences... > Accounts > + > select FreshRSS under Self-hosted > Continue
> * Set `Login:` to Username, `Password:` to Password you've used when activating Google Reader API in Miniflux and use your instance URL (e.g. http://192.168.1.1:1234/) as `API URL:`, click Create
> * You'll find yourself back in the Accounts dialog, feel free to add `Name` so that it shows nicely in the sidebar
> 
> You should be all set!

In API URL field, it should be http://192.168.1.1:1234. there should be no trailing slash. otherwise adding account will fail with error 'Method not allowed'.

**Comment by juju4** [comment]
Currently works following https://miniflux.app/docs/google_reader.html
Connect to server and retrieve feeds list with folders.

**Comment by Cantello** [comment]
Have there been any changes to this method? I just tried it with a working miniflux instance and always get `Network error. Try again later.`
Username and password have been entered as on miniflux's integration page and the API URL is the one that is shown in miniflux without the trailing slash. Should be correct, right?

On iOS it fails as well but with a different error: `The operation couldn't be completed (Secrets.CredentialsError error 1.)`

So it could be a user/password issue? I entered it exactly as on miniflux's intergation section and updated.

<img width="460" height="304" alt="Image" src="https://github.com/user-attachments/assets/5413d144-754a-4532-aef9-3301b9259b9d" />

<img width="478" height="286" alt="Image" src="https://github.com/user-attachments/assets/ee4b27ce-78bc-455d-92c0-523305323ca4" />

**Comment by boggydigital** [comment]
FWIW it's been working well for me since it was added. @Cantello you've mentioned that you've used a URL without the trailing slash - I've checked my instructions above and my setup and I see trailing slash in both cases. Could you check if that helps resolve this (at least for macOS)?

**Comment by Cantello** [comment]
@boggydigital Yeah, unfortunately I checked both with the trailing slash and without, same result. Also Reeder on iOS could not log in, so it is most probably not a NNW issue. Sorry for bringing it up here.

**Comment by boggydigital** [comment]
Sorry to hear that didn't work out! Since your original message mentioned a network error, perhaps validating the general reachability might be a good next step - for your instance, if you hit "{YOUR_MINIFLUX_ADDRESS}/fever/" do you a response back (e.g. "{"api_version":3,"auth":0,"last_refreshed_on_time":0}"? Fever is not the same as Google Reader API (/reader/api/0/*) but that might help narrow down the network issue.
