### ISSUE TITLE
macOS 6.0 b4: title displayed lower in article view 

### ISSUE THREAD

**Issue by sashkab** [Ranchero-Software/NetNewsWire#2916]
Starting with macOS version 6.0b3 and in b4 I have strange behavior: sometimes article's title will be lower than expected:

<img width="1257" alt="screenshot_2021 03 25_203653" src="https://user-images.githubusercontent.com/868842/112560655-0b642000-8daa-11eb-85de-efe7f139171b.png">

After restart, everything goes back to normal.

<img width="1258" alt="screenshot_2021 03 25_203718" src="https://user-images.githubusercontent.com/868842/112560660-0e5f1080-8daa-11eb-8031-903874b5f33e.png">

I can't figure out _when_ this happens, but definitely this started happening after upgrade to b3 and don't remember seeing it with b2 or earlier versions.

**Comment by vincode-io** [comment]
Is this in fullscreen or some max size?

**Comment by sashkab** [comment]
Not fullscreen, windowed. Article text in size Large.

**Comment by greenbuffo** [comment]
This happens to me, too. Windowed mode. If I move one of the splitters, that fixes it. But it happens again (I don't know repro steps). It may happen after I connect or disconnect an external display, which causes macOS to move and resize windows?

macOS 11.2.3 (Apple silicon)
NetNewsWire 6.0.1 (6030)
Light mode

![CleanShot 2021-04-05 at 08 31 06@2x](https://user-images.githubusercontent.com/3219513/113574165-908cd780-95e9-11eb-8cad-44b42c35d142.png)

**Comment by allard** [comment]
This happens to me too and it happens when I go from using my external screen to using my laptop on its own. Didn't now that resizing the columns fixes it so that's easier than restarting that I've been doing. Slightly annoying nevertheless.

MacOS 11.2.3 (not Apple Silicon)
NetNewsWire 6.0.1 (6030), but it's been present in the NNW 6 betas as well but never got around to reporting it.
Dark Mode

<img width="1421" alt="NetNewsWire display bug" src="https://user-images.githubusercontent.com/54212/114319496-24642380-9b55-11eb-8931-d69469c5e67b.png">
