### ISSUE TITLE
Trying to rename a feed causes alert regarding iCloud

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#2921]
The feed for https://eyeondesign.aiga.org is named "Untitled" in the sidebar.
Trying to rename via context menu.
Upon clicking on [Rename] I get the alert (screenshot)
After canceling everything works properly.

NNW 6.0b5 - macOS 11.2.3 (20D91) · MacMini M1

![Screen-Shot 2021-03-27 at 15 21 20](https://user-images.githubusercontent.com/171936/112723816-c1497e80-8f10-11eb-91e1-e2e8417e60bd.png)

**Comment by vincode-io** [comment]
This returns back an unparsable feed when we try to add it. The current error handling doesn't clear the progress bar correctly and incorrectly allows you to add the feed. This feed is in an invalid state and hasn't been added to iCloud, which is why we are getting that error message.

We should correct the invalid feed code so that we don't add the incomplete feed and return a not found error message.

This is a good candidate for a 6.0.1 fix.

**Comment by brentsimmons** [comment]
Is this also an issue on iOS? I put it in the 6.0 milestone, in case it is.

**Comment by vincode-io** [comment]
Yeah, this could happen on iOS too.

**Comment by vincode-io** [comment]
We no longer partially add feeds that have unparsable feed content, like the example given. This fix will be in 6.0.1.
