### ISSUE TITLE
Feature request: Delaying notifications

### ISSUE THREAD

**Issue by geedublya** [Ranchero-Software/NetNewsWire#2943]
Hello! First, as a long time user of NNW, I am *so* glad to see it come back! Thank you so much to everyone who has contributed their time and their talent to this—so grateful! 

If I may offer one feature request: Having choice in which feeds to get notifications from is great; however, sometimes, they come across so fast as to make them essentially useless? 

Until I knew NNW was back, I had been using the also wonderful RSS News Bot. I'm wondering if it's possible to add delays to the notifications as RSS News Bot does? 

Again, my thanks for your wonderful work!

**Comment by vincode-io** [comment]
I don't know anything about RSS News Bot. How does it send notifications?

**Comment by geedublya** [comment]
It sends them through regular macOS notifications: https://itunes.apple.com/us/app/rss-bot-news-notifier/id605732865?mt=12&uo=4&at=10l3Sc&ct=RSSwebsite

It's a great little utility; though I do appreciate NNW's ability to choose which sites send notifications.

**Comment by vincode-io** [comment]
We just use the standard macOS notifications as well. Nothing special here. When we get an article we are supposed to send a notification for, we send it out. We'd get complaints if we didn't do it this way.

If you want to space out your notifications, I recommend setting your refresh interval to 10 minutes. That way you will get smaller batches of them more often.

I'm going to close this issue since there isn't anyway to fulfill this request without also upsetting people who expect their notifications to be timely. Sorry that we couldn't help you here.

**Comment by geedublya** [comment]
Sounds good; For what it’s worth, RSS News Bot offers a preference where users can select the frequency it sends notifications. I believe it’s from 0 to 8 seconds. It can sometimes overload the notifications (particularly noticeable now under macOS 11), but it has the advantage of serving almost as a news ticker. 

Again, thanks for all the great work!
