### ISSUE TITLE
Feeds not always showing in expanded folders

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3040]
App Store Connect report: “just noticing that certain folders are not showing the feeds from within - usually toggling it a few times will fix it and there really isn’t a any rhyme or reason to it - ios latest - iphone 8”

![fits1024x1024](https://user-images.githubusercontent.com/1297121/115946590-25f7ea80-a477-11eb-8476-4b6bcdee6562.jpg)

**Comment by vincode-io** [comment]
Clearly the user has encountered a bug here. I just have no idea how to track it down. I've never seen this happen before and we don't have important information like what kind of account it is and if the filter is active. "there really isn’t any rhyme or reason to it" isn't very helpful.

I don't know what we can do until we a better bug report about this issue.

**Comment by brentsimmons** [comment]
Moving this out of the milestone. Hopefully we can get more info. Or it was a fluke and it won’t happen again.

**Comment by kevinm6** [comment]
> Moving this out of the milestone. Hopefully we can get more info. Or it was a fluke and it won’t happen again.

@brentsimmons I don't think was a fluke, I'm able to reproduce it and now I get how to, because it happened several times with my use of NNW on iOS.

iOS version : 14.6
NNW version : 6.0 (Build 604)

Here's a video that shows how to reproduce the behavior.

https://user-images.githubusercontent.com/72861758/121100634-8d38e680-c7fa-11eb-8c96-025b32aa52d6.MOV

I didn't try on macOS yet.

**Comment by vincode-io** [comment]
This is fixed and will be in the upcoming 1.1 iOS release. cc @jaanus
