### ISSUE TITLE
Firefox doesn’t send URL to NetNewsWire correctly

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3076]
From Slack:

“I'm trying to subscribe to a substack in NNW, and when I enter https://nickmerrill.substack.com/feed in firefox, it hands off to NNW, and 6.0.2 says "The document “feed-2” could not be opened. NetNewsWire cannot open files in the “data” format."”

**Comment by vincode-io** [comment]
What is happening is that Firefox is downloading the RSS file and trying to hand it off to an editor. The user is trying to use NetNewsWire as an RSS file editor. Since we don't support opening RSS files from the file system, the user gets an error.

<img width="486" alt="Screen Shot 2021-05-06 at 8 29 38 PM" src="https://user-images.githubusercontent.com/16448027/117385644-16cb6080-aeab-11eb-8cfb-4e9aa86b783b.png">

Just change TextEdit to NetNewsWire to get the error.

**Comment by brentsimmons** [comment]
Closing this because it doesn’t look like there’s anything we can do about Firefox’s bad behavior. If anyone knows differently, let me know and I’ll reopen this.
