### ISSUE TITLE
Footnote behavior inconsistent/linking remotely

### ISSUE THREAD

**Issue by jasonsnell** [Ranchero-Software/NetNewsWire#3084]
On macOS, this link from sixcolors.com - "Apple execs talk AirTags security, pet tracking" - properly displays an inline footnote when you click on the footnote. However, on iOS in NNW 5.0.5 (56), that link incorrectly opens a web browser window to the URL field of the link, rather than displaying the footnote, scrolling down, or doing nothing.

I have a hard time seeing how following the URL link from the JSON feed is the right behavior for tapping on a footnote link in any case, so this seems like a bug.

JSON feed: https://sixcolors.com/?feed=json

**Comment by babbage** [comment]
There seem to be _two_ bugs at work here. NetNewsWire 6.0 (Build 602) for iOS has already fixed the bug where the footnote pop-over does not display. However, _both_ the current macOS and iOS versions display a separate bug which is responsible for the second part of the behavior you're reporting Jason, which is that the base URL for the article is being treated as the FastCompany external article URL, rather than the original SixColors.com URL. The effect of this is that any 'internal link' that is meant to reference the current page is instead being converted into a link to the FastCompany article, with your footnote `#fn-` id reference appended to it, and then being opened in a web browser window.

This behavior can be seen on both iOS (NNW v6) and macOS by clicking the "back" links at the end of the footnote—either in the footnote pop-up window itself or at the bottom of the article.

Working on why. :)

**Comment by babbage** [comment]
@brehaut this original bug report was re the json feed but Jason Snell happened to mention in the Slack that there is an RSS feed as well. I checked it and it displays the same issue, but because the links are formatted differently the patches that have been committed don't fix the issues in that feed.

In the RSS feed, the footnote back links are in the format: `<a href="https://sixcolors.com#fnref-19490-battery">` with the Six Colors main site as the base URL.

You can see my messages to Jason in Slack re the feed formatting, as I think that arguably this is a feed misconfiguration. However, he may or may not be able/keen to change this. What are your thought on the best way to catch this within another patch otherwise?

**Comment by babbage** [comment]
I guess... maybe we can just construct a css wildcard selector that selects for #fn in the middle of a link, when they are in the .footnotes section? Might not be that complicated?

**Comment by brehaut** [comment]
@babbage Thats unfortunate, but good catch.

Your change to `[href*='#fn']` should be sufficient. I think it’s highly unlikely that within a `.footnote` scope that we would encounter a false positive for that selector so I’m comfortable with that.
