### ISSUE TITLE
Twitter Feed Issues

### ISSUE THREAD

**Issue by voldyman** [Ranchero-Software/NetNewsWire#3108]
I added 2 twitter feeds:
`https://twitter.com/paincomics` -> the dialog closed as expected but i didn't see what was in the feed, just saw paincomics in the sidebar with an unread number

then added `https://twitter.com/dinoman_j` and got an error saying that it's already added.

Both were added using `File`>`New Twitter Feed`

Now i only see `dinoman_j` in the side bar, adding `paincomics` pops an error message saying subscribed.

Clicking on `dinoman_j` shows the "Today" view, and the "Today" views shows the same titles and favicons but with `dinoman_j` as the source.

<img width="1416" alt="Screen Shot 2021-05-09 at 3 04 40 PM" src="https://user-images.githubusercontent.com/2378083/117588398-f03e3d00-b0d7-11eb-9394-9a7773cc4f75.png">
<img width="1416" alt="Screen Shot 2021-05-09 at 3 04 31 PM" src="https://user-images.githubusercontent.com/2378083/117588400-f2080080-b0d7-11eb-8406-18b6c37a4c92.png">

**Comment by vincode-io** [comment]
@voldyman Could you do me a favor and disable your Feedly account and then test again?

**Comment by voldyman** [comment]
So i removed all twitter extensions, removed and installed NetNewsWire again and can't reproduce it.

**Comment by cjenns** [comment]
Not sure if I should open a new issue or post this here. Please advise.

This is regarding Twitter feeds on Version 6.0.2 (6032) in the iCloud and On My Mac accounts.

I have not received any updates today to my Twitter feeds either in my iCloud account or my On My Mac account. Last new Twitter item in my iCloud account is from 5/18/21 10:09 pm EDT.

I have the exact same list of Twitter feeds on my iCloud and On My Mac account and there are no unread items at all listed in the On My Mac account. I restarted my Mac yesterday when I was having an issue unrelated (as far as I know) to NetNewsWire (though it was running at the time) and when I restarted and launched NetNewsWire, all the unread Tweets in the On My Mac account had disappeared. Not marked read; they just aren't there at all, even though there were over 100 unread items in the On My Mac account before I restarted. No new items have been added since. The feeds still show, but they are missing most of the Tweets.

For instance, if I look at @gassee on my iCloud account (Show Read Articles enabled) the most recent Tweet listed is 5/18/21 10:09pm EDT. If I look at that feed in On My Mac (Show Read Articles enabled) the most recent Tweet listed is 5/13/21 2:02pm EDT. On My Mac was working properly the other day.

I wish I could provide a better description of the problem but it's just so broken I'm having a hard time describing it.

**Comment by brentsimmons** [comment]
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.
