### ISSUE TITLE
Twitter Feeds can be dragged into third party provider accounts

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3175]
Once a Twitter feed is added to a local account it can be dragged into a Feedbin account (for example). 

My understanding is that this should be restricted.

**Comment by vincode-io** [comment]
How do we want to handle the scenario where a user is dragging a Folder that has mixed Feeds where some are Twitter and some are Web Feeds? Should we allow the drag and error on the drop for the Twitter feeds (as happens today)? Should we disallow the drop all together?

Now that I think about it, do we even need handle this in the drag-n-drop code at all? You will get a "Feed Not Found" error if you do try to drop a Twitter feed on another type of account because it isn't a valid RSS feed. I feel like we are adding code for something that isn't a problem at all.

**Comment by brentsimmons** [comment]
Even though Twitter is ending its free API, Twitter feeds will still exist in people’s subscriptions, even if they’re inert. That said, I’m not sure, though, that any special behavior is needed here. Needs more thought.
