### ISSUE TITLE
YouTube favicon

### ISSUE THREAD

**Issue by CodingCas** [Ranchero-Software/NetNewsWire#3178]
this is a request for better favicons for youtube feeds. 
now the icon is low rez and the same for every YouTube channel, 
i think the icons will be better with the profile picture of the YouTube chanel. 🙂❤️

**Comment by doamatto** [comment]
I can't seem to reproduce this. I've tried with a few different channels with their official feeds through YouTube and it loaded their channel icons. Can you give an example of a channel that doesn't work?

**Comment by CodingCas** [comment]
> I can't seem to reproduce this. I've tried with a few different channels with their official feeds through YouTube and it loaded their channel icons. Can you give an example of a channel that doesn't work?

i did not know it already is a feature and i just came back here to say that now my icons are loading perfectly!
thanks for your reply.

**Comment by noahmaranesi** [comment]
This issue is happening to me, and has for quite some time; I was unaware that this was a 'bug' (i.e. **not** showing YouTube channel photo) and just not an expected thing to happen (i.e. **showing** YouTube channel photo).

On macOS 12.0.1 (21A559) with NetNewsWire Version 6.0.3 (6035) installed, the photos do not show (just the low-res YouTube favicon), however on iOS 15.1 with NetNewsWire Version 6.0.2 (Build 610) the photos show as expected.
