### ISSUE TITLE
Specific RSS feed only refreshes once when added

### ISSUE THREAD

**Issue by wuedan** [Ranchero-Software/NetNewsWire#3191]
Feed-URL: https://www.shopblogger.de/blog/feeds/index.rss2 

When I add this feed to NNW, it refreshes and shows the latest blog entries, but that's it.
It does not refresh at all anymore after this initial one.

I can delete the feed and re-add it and the same behavior is happening. It doesn't matter if I add it using the iOS or Mac Version.
I am using iCloud Sync.

**Comment by vincode-io** [comment]
There is a problem with this site's RSS feed. When we ask for it, it is returning an HTTP code of 304. That means that the site is telling NetNewsWire that there are no new entries, even when there are. That's why NetNewsWire isn't getting any updated entries. None are being returned from the website. There probably is a problem with how they are handling their conditional get logic.

I suggest you contact the site administrator and let them know that this is happening. You can refer them to this GitHub issue and I'll be happy to help them through the problem.
