### ISSUE TITLE
iOS: iCloud syncing stalls and never finishes

### ISSUE THREAD

**Issue by jsit** [Ranchero-Software/NetNewsWire#3193]
Ever since adding my iCloud account (I have tried removing it and re-adding it), syncing freezes and stalls. The progress bar gets close to about 60%, then immediately jumps back down to around 1% and just sits there.

**Comment by kevinm6** [comment]
Hi, I'm using sync on iCloud since the first beta of NNW on both macOS and iOS, and sometimes I know that it could be a little slow, especially the first main sync.

I suggest you to 
1. backup (export all of your 
   feeds as .opml) from the settings of      
   NNW if you haven't already did it

2. Remove iCloud account on NNW

3. Delete the app

4. On iOS Settings app, go to iCloud and delete the NNW backup on it for your iOS device, wait until it comes back to the previous screen

5. Install again NNW

6. Enable iCloud and import all your feeds from the opml file created previously

**Comment by vincode-io** [comment]
@jsit before you take @kevinm6 's advice and go nuclear, could you tell me more about your setup?

- Is this a new, from scratch iCloud setup or do you already have it set up on the Mac?
- Are you doing an OPML import to start out your account?
- If so, how many feeds do you have?

Initial syncs can be frustrating because of network limits associated with iCloud. We'll figure out a way to get you going. After that, they are pretty smooth.

**Comment by jsit** [comment]
@vincode-io It was an existing iCloud account from the macOS app, with 244 feeds. No OPML import, just flipped on the iCloud account in the iOS app.

**Comment by brentsimmons** [comment]
Our FAQ covers this somewhat: https://netnewswire.com/frequently-asked-questions

**Comment by vincode-io** [comment]
@jsit How many unread do you have? The more of those you have, the longer the sync will take.

**Comment by jsit** [comment]
A few thousand unreads. I've been watching this for a long time (opening multiple times a day since the 6.0 release) and it really doesn't seem to be moving.

![image](https://user-images.githubusercontent.com/643417/123514439-1193c200-d661-11eb-9009-71102203801a.png)

**Comment by vincode-io** [comment]
If you have that much data to sync, you have to keep the app open until it finishes. That can be quite a long time. If you leave the app you have to start over again. iOS only lets us run for 30 seconds in the background. You have to think of it this way. You probably have a couple hundred MB's of sync data to download. iCloud is slow about downloading it. We can only go as fast as iCloud lets us. As tedious as it sounds, you have to keep the app from going into the background on that initial sync. After that it will work without having to be babysat.

**Comment by jsit** [comment]
Thanks! You're right. It continued to look like it wasn't budging past 3-5% or so, then next thing I knew it was just done.
