### ISSUE TITLE
iCloud account issue

### ISSUE THREAD

**Issue by ronzo99** [Ranchero-Software/NetNewsWire#3211]
![Mac NetNewsWIre](https://user-images.githubusercontent.com/22844889/124506409-34c11e80-dd91-11eb-9c98-ee0ad5027299.png)

Mac running latest Big Sur. Error produced when trying to add a feed to iCloud account. I performed the recommended actions to no avail. NNW iCloud account is working fine on my iOS devices, where I have 20 or so feeds, but none of those show up in the Mac version. I have only one Apple ID and iCloud account.

**Comment by vincode-io** [comment]
Deleting the iCloud account in NetNewsWire on your Mac and adding again doesn't show any of the feeds in your iOS devices?

Is there anything unusual about the location of the NetNewsWire data? For example, is it symlinked to somewhere?

**Comment by ronzo99** [comment]
Correct. I don’t think there is anything special about the data. I boot from an external SSD containing Big Sur and NNW.

-- Ron

**Comment by vincode-io** [comment]
@ronzo99 If you don't mind, could you send me the contents of your iCloud account so that I can see what is wrong with it? The location is `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts/2_iCloud`.

Could you also verify that you have `write` permissions to that directory.

**Comment by ronzo99** [comment]
hmm, /Users/ronreuter/Library/Containers/ does not have a com.ranchero… folder. Perhaps I should try reinstalling NNW?

-- Ron

**Comment by vincode-io** [comment]
It should recreate it for you without having to reinstall. Are you able to use the On My Mac account for anything? It would be in that folder too.

**Comment by ronzo99** [comment]
at startup in xcode:

[CloudKit] Error adding account container: Partial Failure: some items failed, but the operation succeeded overall.

I have read/write on Containers folder, but no com.ranchero folders

-- Ron

**Comment by ronzo99** [comment]
i can add a feed to On My Mac, and that works. When I add the same feed in iCloud, it pops up in the Ui, then immediately disappears, then shows the error alert

-- Ron

**Comment by ronzo99** [comment]
Maurice,

Here’s more info, in case it is relevant:
	Using latest source from GitHub
	Building with XCode 12.5.1
	Check for update reports: NetNewsWire 6.0.3b1 is currently the newest version available.

UI behavior:


At around 17 seconds, the iCloud account briefly shows an “Untitled” globe icon, then the Six Colors icon, then nothing, then the error message.

Thanks for your help!

— Ron

**Comment by vincode-io** [comment]
Xcode builds of NNW with iCloud support require setting up and maintaining a personal CloudKit container that won't communicate with the production CloudKit container. This is usually more hassle than it is worth and the source of your errors. Unless you are deadset on working on the iCloud code, I recommend you stick with the -dev build and run a production build of NNW for personal use. You can run both and they won't interfere with each other because they will have different bundle IDs and store their data in separate containers.

**Comment by ronzo99** [comment]
Ah! Thank you!

I’ve been looking at the source code for a long time (taking inspiration from Olof Hellman’s scriptability code) and didn’t realize that I could (or needed to) download the executable from the web site.

I did that just now, and voila! — all my iCloud subscriptions appeared.
Thanks again.
— Ron
