### ISSUE TITLE
Synced feed items between iOS and macOS does not match - Using iCloud account on both devices

### ISSUE THREAD

**Issue by yeradis** [Ranchero-Software/NetNewsWire#3269]
Having iCloud account on iOS and Mac app active

For the same Feed, the amount of items fetched are different
The Mac app shows more items than the iOS version

Specifically, the feed items on the Mac app are 12 and the iOS version only have the latest 2 feed items, 

As and example lets take the `.Net Blog` https://blogs.msdn.microsoft.com/dotnet/feed/

Mac app Version 6.0.3b2 (6034):
<img width="566" alt="image" src="https://user-images.githubusercontent.com/666944/131632683-db54f2bd-3341-4022-8cfa-9e3a928d85b0.png">

iOS app Version 6.0.1 (Build 607):

![image](https://user-images.githubusercontent.com/666944/131632865-7a066290-baf4-4a41-b62e-28ffe98e97ba.png)

The sync issue appears on other Feeds too, not only that one

Is there a way to see what's happening?

**Comment by vincode-io** [comment]
Given the huge number of unread items you have on your Mac, I'm guessing that your iPhone sync has never fully completed. I currently have 3400 unread items and am using 350MB. You have about 6 times that many and are probably using around 2GB.

iCloud is slow about downloading that much data and we only get 30 seconds of background time when you switch away from it on iOS. There just isn't enough time to complete the sync.

My recommendation for you is to mark as many items as read as you can on your Mac to get the number of unread items down. Then do a full sync on your Mac. You then need to try to  get a full sync done on your iPhone. That means you will have to keep NetNewsWire in the foreground until the progress bar fully completes, which can be a very, very long time.

We understand that this is tedious for large collections of feeds on iCloud. Unfortunately due to policy and architectural decisions by Apple for iCloud and iOS, there isn't anything more we can do about this.

The good news is that you only have to do this the first time. After that only differences are synced which will go much faster for you.

**Comment by vincode-io** [comment]
@yeradis Did you ever get your iPhone in sync?

**Comment by vincode-io** [comment]
I'm going to close this since it doesn't appear to be a bug in NNW. We can reopen if that proves otherwise.

**Comment by msongz** [comment]
the unread items matters on sync?
on my side , i just need it sync the opml in devices, not the reading status

**Comment by msongz** [comment]
and how can i know my feed synced or not in icloud?
every time i add a feed, my other devices are nothing happend
