### ISSUE TITLE
M1 with a large OPML import beachballs

### ISSUE THREAD

**Issue by sgchipman** [Ranchero-Software/NetNewsWire#3282]
I've recently updated to an M1 Macbook Air, and after exporting my subscriptions from my Intel Mac, and importing them to the M1 mac, the install of NetNewsWire (6.0.3) on the M1 immediately beachballs and becomes unresponsive after selecting a folder. It doesn't matter if there are 4 unreads or 1000+ in the selected folder.

I've attached the OPML to help reproduce. Do let me know if I can provide any other information to aid in debugging.

[Subscriptions-OnMyMac.opml.zip](https://github.com/Ranchero-Software/NetNewsWire/files/7151001/Subscriptions-OnMyMac.opml.zip)

**Comment by vincode-io** [comment]
I can recreate this using your OPML file on an Intel Mac.

Have you recently added any new feeds? One of them is throwing a monkey wrench into our works.

**Comment by vincode-io** [comment]
The feed that was causing us problems was "Amazon.com Gold Box Deals". I've commented it out in your OPML file so that you can import it and use NetNewsWire again.

[Subscriptions-OnMyMac 2.opml.zip](https://github.com/Ranchero-Software/NetNewsWire/files/7151139/Subscriptions-OnMyMac.2.opml.zip)

You will probably have to manually delete your On My Mac account. At the terminal you will want to run this. You may need to navigate into the directory directly if that command is off for some reason. After that you should have an empty On My Mac account that you can reimport your OPML into.

```rm -rf ~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application\ Support/NetNewsWire/Accounts/OnMyMac```

**Comment by vincode-io** [comment]
Upon further investigation that "Amazon.com Gold Box Deals" doesn't have any entries newer than 2018, so it is of no practical use.

The problem that we are having is that it is a massive feed. It is 9MB total which is causing us database performance issues.

We don't have any immediate plans to address this edge case at this time, but we are keeping this issue open incase it becomes a more common problem.

**Comment by sgchipman** [comment]
Thank you so much! And thanks for all the work you do on the app.

**Comment by brentsimmons** [comment]
That Amazon feed no longer exists. Closing this.
