### ISSUE TITLE
Duplicate feed entry

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#3286]
Feed URL: https://www.netlify.com/blog/index.xml (confirmed that the feed has no duplicates)

I've seen this with multiple articles in this feed, although only the latest article appears duplicated at any given time.

![image](https://user-images.githubusercontent.com/25517624/133265118-4b0d75d2-36c5-494c-85e0-d7857bf838b2.jpeg)

**Comment by stuartbreckenridge** [comment]
What's happening here is that Netlify are using the URL as the GUID and when that changes it appears as a new entry (or a duplicate entry if it's already been picked up). For example, see the below URLs for the first two articles (which look like duplicates in the timeline):

https://www.netlify.com/blog/2021/09/13/build-your-own-online-shop-with-next.js-and-shopify/

https://www.netlify.com/blog/2021/09/13/build-a-your-own-online-shop-with-next.js-and-shopify/

**Comment by vincode-io** [comment]
Technically those are two separate articles based on both URL and GUID. Maybe we could hash the content and deduce based on that? Even then it would be a performance drag and only useful for a very, very small number of articles.

I'm going to close this issue since trying to deduplicate articles with different GUID's and URL's isn't practical. We can reopen if someone has a better idea.
