### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by no0ID** [Ranchero-Software/NetNewsWire#3310]
The following feeds are imported to NetNewsWire but tapping on any news to see the content, the link wants to open the article in iTunes. How to adapt one of these feeds to open the article in NetNewsWire please? Thanks!

https://rss.itunes.apple.com/api/v1/sk/movies/top-movies/all/25/explicit.json

https://rss.itunes.apple.com/api/v1/sk/movies/top-movies/all/25/explicit.rss

https://rss.itunes.apple.com/api/v1/sk/movies/top-movies/all/25/explicit.atom

**Comment by vincode-io** [comment]
Did you try adding them in NetNewsWire using the Add Web Feed option?

**Comment by no0ID** [comment]
> Did you try adding them in NetNewsWire using the Add Web Feed option?

Yes and is working. The NNW downloadS the individual news, but the problem is to open any of them.
When tapping the title a search for iTunes is started. See the attachments.
![ADB201E7-25FA-433A-B5DF-56E1FA43EE22](https://user-images.githubusercontent.com/79188024/135726631-fb996b58-7a7e-4d87-9403-3d6ff42f75cf.png)
![3FBDAB9C-2B83-4287-82A7-E6B81663728B](https://user-images.githubusercontent.com/79188024/135726632-79369824-42a7-4d67-be3e-7c341154549f.png)

**Comment by babbage** [comment]
Hi no0ID... I took at look at this feed. What you're seeing in NetNewsWire is the full content provided within the feed itself.... all they provide in the title is the movie name, year and I guess the name is the director? And then in the body, just the movie name and year again. When you get to the content on the iTunes Store, there is a paragraph-long movie description... but those details are not in the feed... 

When I click on the links on macOS, it takes me to the page for those movies on the web, not in the desktop browser. That is true if you click on those links on the web and the same thing thus happens when you click on them in NetNewsWire. I see however that you're on the iPad. On the iPad, links to iTunes Store content open directly in the iTunes Store app rather than in Safari... 

So I'm afraid this is all working as expected... if you want to view those movie details, you may have to reinstall the iTunes Store app.

**Comment by no0ID** [comment]
Weird, Apple way.
Thank you for help and explanation.
