### ISSUE TITLE
Feature request : 5 minute refresh or more configurable refresh rate.

### ISSUE THREAD

**Issue by pateljoel** [Ranchero-Software/NetNewsWire#3372]
I am loving NetNewsWire at the moment and I can see in the refresh interval code in [RefreshInterval.swift](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Shared/Timer/RefreshInterval.swift) that the lowest is every 10 minutes, would it be possible to make this configurable to at least 5 or 2 minutes? Or perhaps certain feeds can be lower or higher than others.

Thanks.

**Comment by brentsimmons** [comment]
The RSS spec says to limit refreshes to once per hour — and I understand why: it’s so we don’t overwhelm the servers providing the feeds. Nevertheless, we’ve decided that 10 minutes is probably okay.

With 10 minutes, the average amount of time between publication and the article arriving in NetNewsWire is 5 minutes. What’s the use case for getting news even more quickly?

**Comment by fmocking** [comment]
I was seeking this feature because my need for higher refresh rates stems from platforms with fast update frequencies, like Reddit. It becomes crucial when trying to respond promptly to posts. I'm sure there are similar use cases where people want to access new content quickly. Allowing users to input custom timings to suit their needs would be ideal.

**Comment by climardo** [comment]
I would like to be able to to set some feeds to update only once a day, and ignore "update all". So not quite what OP was requesting, but similar. Also, lol and rip reddit

**Comment by brentsimmons** [comment]
We will stick with 10 minutes as the minimum refresh interval.
