### ISSUE TITLE
Background App Refresh not updating RSS feeds in the background

### ISSUE THREAD

**Issue by coopercollins** [Ranchero-Software/NetNewsWire#3389]
I noticed NetNewsWire has Background App Refresh support which I’ve turned on in the settings. I’ve subscribed to some RSS feeds and when I close the app it’s not updating the RSS feeds in the background instead I have to launch the app to check for new unread items. I would like the app to check the RSS feeds in the background and provide a notification if there are new items, can you please implement this?

**Comment by vincode-io** [comment]
Are you force quiting NetNewsWire? If so, it won't run in the background.

**Comment by coopercollins** [comment]
Yes I’m force quitting NetNewsWire. I force quit the Gmail app and it still notifies me when I receive a new email. Can NetNewsWire have that same level of functionality?

**Comment by vincode-io** [comment]
The Gmail app is sending you remote notifications from a server. It isn't using background refresh. Since there isn't a server component to NetNewsWire, we can't send remote notifications.

Force quiting NNW is why you aren't getting background refreshes. Even then, they only happen when scheduled by iOS which tries to conserve battery life by only doing refreshes when it thinks you will need them.
