### ISSUE TITLE
Server Rejected Request

### ISSUE THREAD

**Issue by ednl** [Ranchero-Software/NetNewsWire#3397]
Hello, thanks for the great work on the apps. Today, all three of my installs (Mac, iPadOS, iOS) stopped updating and gave the error as in the title. I imagine it might be one feed with a wonky server blocking everything, but how could I check? The error message is too general to know what's really going wrong. Or is it maybe an iCloud issue? I sync all feeds via iCloud and it has enough room.

**Comment by brentsimmons** [comment]
We believe it’s a temporary iCloud issue.

https://twitter.com/NetNewsWire/status/1480613320172314624

**Comment by I7T5** [comment]
Hi, I'm seeing the same error every time I manually refresh on Mac, iPadOS, and iOS today. Feeds came into Mac, even though it did not allow for manual refresh. No feeds came into iPadOS and iOS. Could it be because I changed the country/region of my Apple ID from China to US, moving the iCloud data? (iCloud data is stored in China if your Apple ID's set in China). Or because I traveled from China to US?

The tweet's deleted.
