### ISSUE TITLE
Empty description attribute in webfeed Subscriptions.opml for OnMyMac account

### ISSUE THREAD

**Issue by wgroeneveld** [Ranchero-Software/NetNewsWire#3406]
Hi there,

I'm of course totally unaware of the history of the code and the philosophy behind NetNewsWire's way of working, so hear me out. 

I'd like to audo-parse the `Subscriptions.opml` file. The problem is, somehow, the attribute description is empty. See WebFeed.swift, line 324:

```
var s = "<outline text=\"\(escapedName)\" title=\"\(escapedName)\" description=\"\" type=\"rss\" version=\"RSS\" htmlUrl=\"\(escapedHomePageURL)\" xmlUrl=\"\(escapedFeedURL)\"/>\n"
```

All RSS feeds contain, next to the `<title/>`, that gets parsed and turned into the `escapedName` (editable in the GUI), also a `<description/>` tag with very useful information on what the feed is about. I'd ideally like that to get saved in the `.opml` file. 

I tried following the flow in `AddFeedController.swift` but I can't figure out where everything gets parsed... 

Is something like this possible?
I'd love to take a jab at it myself with a bit of guidance!
Cheers,
Wouter

**Comment by vincode-io** [comment]
I think it would be possible, but might not work consistently. You would have to add a `description` property to `WebFeed` and populate it using either data from our local parser or the syncing service that the feed is being added to. The description doesn't look like it is being captured in our local parser for some feed types (I don't know if they aren't part of the spec). I also don't know which, if any, of our syncing services provides it.

Adding the description will be pretty involved. You will have to update all our `AccountDelegate`s so that it works consistently and would have to get familiar with all our syncing services (including iCloud). It is a pretty complicated enhancement just to enhance the `Subscriptions.opml` file.

I don't know why you are wanting to parse the `Subscriptions.opml` file, but you might be better off downloading and parsing the RSS feeds directly yourself.

**Comment by wgroeneveld** [comment]
Hmm, thanks for the feedback on how the internals work. It sounds like it's rather involved indeed. 

As for my reason to parse the `.opml` file: for the moment, it auto-converts into a list of links on my website, a "blogroll" so to speak. Since NetNewsWire is my starting point to follow others, I wanted to export those into the site. Having the information there is a lot less contrived than having to fetch the feeds myself and parse a `description` (or something else) from it.
Perhaps I can add a pre-processing step that does just that as not to take everything from the NetNewsWire-specific file for granted. 

Thanks again!
