### ISSUE TITLE
iCloud will not sync on iOS

### ISSUE THREAD

**Issue by Melonking906** [Ranchero-Software/NetNewsWire#3417]
I have NNW on 2 macs and iPad and an iPhone, all syncing feeds via iCloud. The 2 macs have no issue communicating with each other or feeds, however the iPad and iPhone will not update feeds (They wont even fully list what feeds I'm subscribed to). The loading bar just sits at the very start and never moves.

Its been like this for at least 8 months, I though for a long time it was just an issue with my iPad (I did try reinstalling the app a few times), but having recently gotten a new iPhone, it has exactly the same issue right out of the box.

At first I thought it was a conflict with ProtonVPN, however disabling that does not fix the issue. My next best guess is that something about my iCloud feed library is corrupt in some way, but I'm not sure what to do about that.

**Comment by vincode-io** [comment]
Initial sync with iCloud can take a very long time. This is due to a limit in how fast we can download iCloud data. This is especially true if you have a large number unread items.

You have to keep NNW in the foreground while the initial sync happens or you have to start the sync over again. This is due to a limit in how long we can run NNW in the background on iOS.

Please remove you iCloud account and add it again, keeping NNW in the foreground until it is done. This will likely take a good deal of time. It can literally take an hour or more. We understand this is tedious, but we don't have any better options on iOS due to system resource limitations.

I'm going to close this issue since we understand well that iOS initial syncs take a very long time. Please comment on this issue, even after I close it, and let us know how you do.

**Comment by Melonking906** [comment]
Ah thank you for your fast reply, leaving it open and the screen on did fix it! Although I realize now my mistake was trusting iCloud :P I took the opportunity to install FreshRSS and its instant! Although not exactly user friendly to setup..

**Comment by vincode-io** [comment]
Yeah, the other syncing services don't bandwidth constrain the way that iCloud does.
