### ISSUE TITLE
MacOS - No deleting of read article in "All unread" section when clicking the refresh button

### ISSUE THREAD

**Issue by Phipsiii** [Ranchero-Software/NetNewsWire#3439]
Hello,
I normally use the smart feed "All unread" on my Mac. In the past the read articles were deleted when I clicked the refresh button. This is no longer working. Now I have to switch in another section and click back to "All unread". Maybe is there a bug? The "Hide read articles" button is greyed out at "All unread". So I do not see any option to change it.
Thanks for helping hands.

**Comment by vincode-io** [comment]
Are you maybe misremembering? We've never clear a Timeline of read articles on the Mac. We have an option to do it on iOS though. 

The read article filter isn't enabled on All Unread because clicking it would pull all articles, from all feeds into the timeline at once. That isn't sustainable from a performance perspective. 

I don't think we have a bug here, so I'm going to close this issue. Feel free to comment on this issue off you have more questions.
