### ISSUE TITLE
Lost state due to iCloud unrecoverable error

### ISSUE THREAD

**Issue by jacobpledger** [Ranchero-Software/NetNewsWire#3560]
On macOS I went to rename a feed and a dialog appeared saying that there was an unrecoverable error with my iCloud account and to remove and re-add the account. As far as I could tell sync on that account was still working fine, however.
I didn't want to leave an error like this alone lest it cause more problems later, so I removed and re-added the account as instructed. NetNewsWire then synced the feeds back down, but reset the read/unread/starred status on many (but not all?) of them and then synced *that* back into iCloud, so I lost a bunch of state data.

I wish I had steps or something to reproduce this but I have no idea what caused it other than something squirrely with iCloud and the handling thereof. Let me know if there's more info I can try and provide.

**Comment by vincode-io** [comment]
Unfortunately if there is a problem on Apple's end with iCloud there isn't much we can do to recover except either try again later or rebuild the iCloud account. Since you weren't able to communicate with iCloud there was no way for NetNewsWire to save your article statuses to iCloud. Sorry, but there really isn't anything we can do to make this situation any better.
