### ISSUE TITLE
Widget data should be written to disk when things change, and not when entering background

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3567]
The app sometimes crashes, via watchdog termination, on trying to fetch widget data when moving to the background.

Instead, we should write out widget data when the app is in the foreground when things change such that the widget data is stale. (Also write it out as the last step in a background refresh.)

We should not attempt to fetch widget data when the app is moving to the background.

**Comment by stuartbreckenridge** [comment]
Will this not prevent the widget refreshing when the app is updating via a background refresh?

**Comment by vincode-io** [comment]
@brentsimmons To correctly keep the Widget data in sync, I had to observe `StatusesDidChange`. This is because there are unread counts on some of the Widgets and the Starred Widget needs to know when something is starred/unstarred.

So that we weren't perpetually fetching data and writing it for Widgets, I used a `CoalescingQueue` with a 5 second interval. This works well, but if someone changed an Article Status and then immediately moved NetNewsWire to the background, the Widget Data would be stale. How I handled this was that I execute Widget encoding if the data is stale.

This means that there is still the potential for the watchdog crashes to show up. The only other alternative that I can think of is to just let the Widgets be wrong about the last 5 seconds (at most) of activity.

**Comment by vincode-io** [comment]
We are still getting a number of crashes with the latest build. I don't have access to the NetNewsWire crash logs using the Xcode organizer and the ones on App Connect don't have crashlogs.

I was able to see a few crashes on my own devices that were the WidgetDataEncoder trying to write data out as NetNewsWire moves to the background. I recommend that we stop trying to keep the Widget data fresh on moving to the background and just let it be inaccurate about the most recent article status changes.

**Comment by stuartbreckenridge** [comment]
@vincode-io
What does the widget do when it crashes from a UI perspective?

**Comment by vincode-io** [comment]
The widget just doesn't have updated data.

**Comment by stuartbreckenridge** [comment]
Are you able to tell when it crashes?

On entering background or during a background refresh?

**Comment by vincode-io** [comment]
It is the same problem we've always had. It is when we are moving to the background state. It doesn't matter if that is happening during a background refresh or not.

**Comment by stuartbreckenridge** [comment]
I'll spend a bit of time looking at this over the next few evenings. It doesn't seem like there's anything wrong with our code, which is the most frustrating part.

**Comment by vincode-io** [comment]
The only thing we need to do is pull the line where we force the write to disk when we go into the background. The widgets will still get updated, the just won't have the last few seconds of user activity accounted for.

**Comment by stuartbreckenridge** [comment]
I don’t disagree. But…that 5 seconds should be solvable. Sent from my iPhoneOn 5 Oct 2022, at 21:00, Maurice Parker ***@***.***> wrote:﻿
The only thing we need to do is pull the line where we force the write to disk when we go into the background. The widgets will still get updated, the just won't have the last few seconds of user activity accounted for.

**Comment by stuartbreckenridge** [comment]
How the widget is _currently_ updated puts it out of sync with the application badge at certain times (in this example, the widget has three unread, while the badge has two — the badge is correct). 

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-08 at 10 05 04](https://user-images.githubusercontent.com/7046652/194682613-3abc4deb-ac80-4073-ab3d-be6027371bfe.png)

Removing the call to encode the widget data when the application enters the background permanently puts it out of sync. 

Is this an acceptable compromise when we haven't seen users reporting widget crashes?

**Comment by vincode-io** [comment]
It doesn't go "permanently" out of sync. It only loses the last 5 seconds at most of user activity that happens. My last commit does prevent the WidgetDataEncoder from running as we move to the background.

There is a bug in your screenshot that I didn't understand at first. The app badge shows 2 unread articles which matches the number of unread articles shown which is also 2. Why then does the widget have a footer that says "+1 more unread article"?

This seems to happen when the `CoalescingQueue` fires immediately when adding something to it and another `StatusesDidUpdate` comes right on its heels. The widget data gets wrote out immediately with data that may be stale. To work around this, I used a DispatchWorkItem to debounce so that we never fire immediately when a `StatusesDidUpdate` notification happens.

**Comment by stuartbreckenridge** [comment]
On a fresh install, I ran this through UI tests (created a new target) to simulate launch -> go to All Unread -> select top article in table view (wait 3s) -> back to all feeds (wait 1s) -> out of app -> wait 30s -> repeat (x50) [25 mins of testing]. 

No widget crashes to report, and it remained in sync.
