### ISSUE TITLE
Article display is suddenly wonky on boingboing.com

### ISSUE THREAD

**Issue by joncallas** [Ranchero-Software/NetNewsWire#3585]
Boingboing.com has recently started displaying oddly -- title, then a large gap of white space a good 15+cm, and then the text.

I am sure the the underlying problem is their issue, not yours, nonetheless, it would be nice if you looked at it and would see if you can make it work better.

They also do not do the right thing when one clicks reader view, and haven't for ages. This is why I think they have a wonky web site. Nonetheless, NNW is my way to read them and it's annoying.
<img width="725" alt="image" src="https://user-images.githubusercontent.com/2214764/171987191-c4657802-3214-448f-a443-e6082863d32d.png">

**Comment by vincode-io** [comment]
That gap is actually an image that you can't see. The problem is that the `srcset` attribute of the `img` tag is set with a base64 encoded data gif. As best I can tell, this is supposed to be a placeholder image for WordPress lazy loaded images. Since WordPress lazy loading doesn't work in NetNewsWire, it never gets replaced.

Other RSS readers that I tested also seem to have this problem.

The solution to this problem is for Boing Boing to remove the `srcset` attribute.

**Comment by joncallas** [comment]
Addendum:

I contacted Boing Boing and got a reply:

>You’ve actually solved the problem! We can fix it now!

Thank you for being the ones who actually solved the problem.

**Comment by vincode-io** [comment]
Thanks for the follow up!

**Comment by joncallas** [comment]
And thank you for doing all the work. There's also funny stuff on their site about Reader View, that often does the wrong thing, as well. I've mentioned it to them.
