### ISSUE TITLE
Feature Request: Register NetNewsWire to handle http and https, so Safari's Develop menu offers NetNewsWire in the Open Page With options.

### ISSUE THREAD

**Issue by faisal** [Ranchero-Software/NetNewsWire#3597]
Feature request: NetNewsWire for macOS registers itself as able to handle http and https, thus including NetNewsWire in the list of target browsers in Safari's Develop > Open Page With menu.

If I recall correctly, NetNewsWire Classic used to show up in Safari's Develop > Open Page With menu. This provided a trivial workflow for subscribing to the feed of a page or site one was currently reading, and didn't require I load an extension in Safari.

**Comment by faisal** [comment]
https://github.com/faisal/NetNewsWire/commit/d4361ad6d521a2e68ca74b164e22e90662dd9df3

**Comment by faisal** [comment]
PR: https://github.com/Ranchero-Software/NetNewsWire/pull/3598

**Comment by vincode-io** [comment]
Was the Develop menu the only thing impacted by this? I'm just curious if it makes NetNewsWire show up anywhere else in the system as an HTTP/HTTPS handler that we might not want it to.

We do have a Share Extension that is system wide that is used for this functionality currently. The Share menu could be used instead of the Develop menu to subscribe in NetNewsWire if that is what we are trying to do.

**Comment by faisal** [comment]
It wasn't in System Preferences'  list of default browsers when I've looked. Are there other places that reference the list of available browsers? I expect if there is, someone might be able to send NNW a URL it can't really do anything with, but that seems a low risk and also easy for the user to deal with if it happens.

The original NNW had this functionality for years and I don't remember it ever being a problem.

The Share Extension is also useful and I use it on iOS. I hadn't known of the macOS one until this discussion, so will give it a shot. I do find the form in NNW itself makes more sense than the popup in the Share Extension, but I'm not sure how to deal with that other than adding more code to the extension.

**Comment by vincode-io** [comment]
The Share Extension has all the functionality of the Add WebFeed dialog except being able to edit the URL. That isn't necessarily in the Share Extension since the URL comes from the App is launched from.

I'm just concerned about registering for schemes that may have unintended side effects. I honestly don't know if there are any. I just think it safer to not include them if our only benefit is being added to the Safari Develop menu and we have an alternative solution that provides the same functionality.
