### ISSUE TITLE
[feature request] additional app icons

### ISSUE THREAD

**Issue by cyb3rspace** [Ranchero-Software/NetNewsWire#3614]
More app icons to change the aesthetic, maybe a black icon or some user submitted ones?

**Comment by eperitus** [comment]
I'd love to see this too - the default icon's blue is close to the App Store, and Mail's own blue, along with numerous (I counted 7 on my small list of installed apps) third party apps.  It would make it easier if we could customise it and have a uniquely-coloured icon for NetNewsWire - would make NetNewsWire really stand out in the sea of blue.  Apollo does a great job at this.

**Comment by vincode-io** [comment]
NetNewsWire is an open source project manned by volunteers. We are extremely fortunate that a well known, highly skilled designer did our app icons for free. Good icon design takes a lot of time and effort. Our designer is very busy and we can't expect him to spend all his free time making icons for us.

Apollo is a commercial product that can derive additional sales and revenue by including whimsical icons. That is how they pay for the designers to do them. This is a very different model than an open source one.

Since we are committed to keeping NetNewsWire free and open, this feature will probably not happen.
