### ISSUE TITLE
Option to disable swipe to next article on iOS?

### ISSUE THREAD

**Issue by eperitus** [Ranchero-Software/NetNewsWire#3624]
It seems like every day I accidentally swipe to the previous or next article.  I never want to swipe between articles.  Is it possible to add an option disable this feature?

**Comment by vincode-io** [comment]
One of the things we try to do with NetNewsWire is to keep our options as simple as we possibly can. This means there is a high threshold for us to add a new one. This means we need to be adding it to the benefit of a large number of users. We do this because too many options confuse and frustrate users, causing them to give up and move on.

If you have shaky hands or some other disability that is causing you to accidentally swipe, this article may help you. https://www.imore.com/how-use-touch-accommodations-iphone-and-ipad

If this doesn't help, please provide us with more information about what is causing the accidental swipes. Maybe we can provide a solution that doesn't include adding a new option. If that is the case we can reopen this issue.
