### ISSUE TITLE
App launches on an old article even if already read

### ISSUE THREAD

**Issue by Mr-Camargo** [Ranchero-Software/NetNewsWire#3639]
This has been a long lasting bug. It happens whenever I read any article.

I close the app and whenever I open it up again, it opens up in the same article. This issue can last for months, and there is no way to fix it unless by removing and re-adding the feed such article is from.

My versions are:

- iOS 16.0 Developer Beta (20A5328h)
- NNW 6.0.2 (Build 610)

Please note that even if I have a developer build of the OS, this bug has been occurring since stable releases of iOS 15.

I really hope it can get fixed. Thank you!

**Comment by vincode-io** [comment]
Do you mean it opens the last viewed article or a different one?

**Comment by Mr-Camargo** [comment]
@vincode-io a read article from looooong ago, like from months ago.

It is always the same. And it doesn't change even if you read another one.

Something I observed is that it happens on **the first article you read completely**.

**Comment by vincode-io** [comment]
This issue is happening for you on both macOS and iOS? Are you force quitting NetNewsWire by any chance?

We don't track when you read an article to the end. We only store which article that you have currently open, if any, when the application closes.

**Comment by Mr-Camargo** [comment]
I do not use NNW on Mac 😅, but sincerely I do not remember wether I force closed the app when I was reading that specific article.

But even if I close the app gracefully, not currently reading any article, whenever I launch the app this very article pops up again.

**Comment by vincode-io** [comment]
Is this on iPad? If so, do you have multiple NetNewsWire "windows" open at the same time? You can check by going into the application switcher.

What might be happening is that you have more than one "window" open and are only updating one of them. Then when you launch NetNewsWire again, the first one is still where it was last time because it hasn't changed. Only the second one has.

**Comment by Mr-Camargo** [comment]
Nope. It is on an iPhone.

In the meantime, I did confirm that if you force quit the app while reading an article _does_ makes the app stuck in that same article until you erase the feed the article is from. (I did so by reinstalling NNW a few hours ago)

So I pretty much think the bug was caused by me 😅

However, it is very stressing that the same article persists in the "Currently Reading" memory for a ridiculous amount of time even if you start reading another one.

Don't you think it would be a good idea to reset or reassign the variable that retains the currently reading article after a long period of time (say, two weeks)?

I do not know if such mechanism is in place already, but I would love to help fix it if you decide it is a good idea and can be actually helpful for other users.

**Comment by vincode-io** [comment]
The application state is requested by iOS itself when the application normally quits. It is then pushed to the application when it is launched again. There isn't anyway for us to overwrite it.

If you force quit the app, iOS will never request the state and it will always be the same and will always be the same when launching the app.

Deleting the feed doesn't actually get the state unstuck. It just prevents NNW from finding the article because it was deleted, so we default to having no state.

Force quitting is so bad for so many reasons. It actually increases battery usage when you do it and it messes up so many application behaviors. Please stop.
