### ISSUE TITLE
iOS: Feature request: Refresh interval setting

### ISSUE THREAD

**Issue by lkhrs** [Ranchero-Software/NetNewsWire#3649]
I think it would be great if the iOS app had preferences to limit the refresh interval, similar to the macOS app. 

This would reduce data and battery usage, and the amount of requests to subscribed feeds.

On iOS, the current behavior of NetNewsWire is to refresh all feeds on launch (there also seems to be a timeout before automatic refresh happens again on launch). 

Proposed behavior: If the interval is set to 1 day (example), the iOS app will not automatically refresh all feeds until the next day.

Additionally, I suggest adding an option to disable pull-to-refresh when a refresh interval is set, so that pulling-to-refresh would remove read articles from the list without refreshing all feeds.

**Comment by vincode-io** [comment]
We always sync when launching on macOS. This is because usually people want the most current articles when they are using NNW. On iOS, we changed this behavior slightly so that we aren't syncing every time you switch apps away from and back to NNW. It will only do the sync if it wasn't done in the last 15 minutes.

We schedule background syncing for every 15 minutes, but iOS will optimize this for battery life and usage. It uses machine learning to try to understand when you are most likely to open NNW next. Since we don't have any real control over when the background sync would happen, it would be confusing to users if we gave them the option to set it and it never worked.

As for disabling pull to refresh, we try not to add so many setting that it gets complicated and confusing for users. That means that there is a fairly high bar for adding a new setting. Disabling pull to refresh doesn't seem like something most users would care about and in my opinion doesn't meet the qualifications for a new setting.

@lkhrs I don't think your ideas are bad or that they don't lack merit. I can see how they would be useful to you. I just think they conflict with trying to keep NNW clean and uncluttered. I'm sorry, but many apps lose their way by trying to be all things to all people. We don't want that for NNW.

I'm going to close this issue only because I don't think we would implement these suggestions. I don't have the final say on these things though. @brentsimmons may disagree and reopen this issue if he feels like we should add these features to NNW on iOS.

**Comment by lkhrs** [comment]
@vincode-io @brentsimmons does sync = refresh? I was under the impression that iCloud sync and refresh of subscribed feeds were two different things.

To clarify, I'm talking about refreshing subscribed feeds, which is both battery and data intensive.

**Comment by vincode-io** [comment]
Syncing and refresh are the same thing.

**Comment by vincode-io** [comment]
Well... Syncing with iCloud is technically a different process than refreshing feeds, but we have to do them both together to make things work correctly. The process that we do them both at the same time is sometimes called syncing and sometimes refreshing. This is when you see the progress indicator at the bottom of the screen.

**Comment by lkhrs** [comment]
Understood. In that case, if the two can’t be separated, it looks like the alternatives would be to either stop using iCloud sync and switch to one of the supported feed aggregators, or just disable cellular data for NetNewsWire. The latter is not ideal since images aren’t downloaded, but that’s a separate issue :)

Thank you for clarifying, and I appreciate all the hard work on NNW!

**Comment by vincode-io** [comment]
I would be interested in seeing how much battery savings you get by switching to a feed aggregator. I know it should save some, especially on cellular, but I wonder how much.

Maybe a better enhancement request for you would be to disable syncing on iOS when using cellular data. I could see that being useful for both preserving battery life and for those that have data caps on their cellular plans.

**Comment by electr1fy0** [comment]
A manual refresh only toggle would be nice though.
