### ISSUE TITLE
Does not icloud sync on iPad Pro

### ISSUE THREAD

**Issue by zoulhh** [Ranchero-Software/NetNewsWire#3656]
No articles on iPad Pro. Deinstall / install no change. Icloud is ON. Works perfect on iPhone and Mac though. 

Regards

Mick

**Comment by brentsimmons** [comment]
Is it syncing? Sometimes iCloud syncing can take hours, especially on a new device or on a device where you haven’t used NetNewsWire in a while.

**Comment by zoulhh** [comment]
The iPad is syncing. NetNews also syncs the feeds but not a single feed content. Even not after days or weeks.

**Comment by hansonis** [comment]
Same issue on my iPad Air. No syncing after hours or even days. Seems like there is a bug on iPads.

**Comment by vincode-io** [comment]
Is the status bar actually completing on your iPad? If not you may need to turn off the display lock and leave NetNewsWire running in the foreground until it completes. As @brentsimmons mentioned it can literally take hours to complete if you haven't synced in a long time.

Before bed, turn off the display lock. Start NetNewsWire and leave it on the screen. In the morning it will have synced again.

After that, as long as you sync regularly, you won't have this problem.

**Comment by hansonis** [comment]
Thanks for your answer. No, status bar isn't completing. It's stuck on first step. I'll try your tip now.

**Comment by hansonis** [comment]
Don't know why, but it actually works now on my iPad Air. Thanks for helping me.

**Comment by vincode-io** [comment]
iCloud sync technically isn't broken, but the user experience can be so bad that we consider it broken. We understand how to the user it looks like nothing is happening during the sync, even when it actually is.

I'm going to close this out because this is a pretty well known issue that we are actively working on a solution for. #3566 is the issue we are tracking it with. The title says something about initial sync, but it is the same problem that can happen if you haven't synced in a while.
