### ISSUE TITLE
Add a request limit/throttle for power users.

### ISSUE THREAD

**Issue by cocoonkid** [Ranchero-Software/NetNewsWire#3723]
I am having the issue that NNW is pushing thousands of DNS requests at once when refreshing feeds.  This causes issues with pihole and probably many other services/firewalls/proxies.

In my case I am getting blocked for a minute :-)

One can clearly see the spikes caused by NNW on the scheduled refreshes.
![image](https://user-images.githubusercontent.com/43231640/198136134-184df23f-dff9-4760-9de0-e5ecd333997a.png)

It would be great to add an option for throttling or batching. At least when a certain threshold of subscribed feeds is reached.

I can see that this will cause issues most users won't immediately understand or cause blocks and false positive alerts for admins of networks etc.

Of course that might only be me.

Thank you for your consideration and the great software you provide for the community!

**Comment by vincode-io** [comment]
We have discussed adding this feature in the past and decided against it. We want to keep NNW as easy to use as possible and a power user feature like this could be confusing to the average user.

Power users can configure the software that is throwing the errors so that they are more tolerant. 

The pihole limit of 1000 requests every 60 seconds is much too low for someone who clearly is trying to sync as many feeds as you have. Change the DNS `RATE_LIMIT` configuration and you should be fine.

https://docs.pi-hole.net/ftldns/configfile/
