### ISSUE TITLE
NY Times link behavior differs on iOS and iPadOS

### ISSUE THREAD

**Issue by ray19826** [Ranchero-Software/NetNewsWire#3771]
I have the NY Times app on both my iPhone and iPad. In NetNewsWire, I subscribe to the NY Times RSS feed (iCloud sync). On both devices, in NNW settings, "Open Links in NetNewsWire" is selected.

On iOS, when I click a NY Times link from NNW, it opens in the in-app browser. On iPadOS, it opens in the NY Times app instead (which I would not like to occur).

This a bug? Is there a setting I'm missing? Thanks!

**Comment by brentsimmons** [comment]
I’m not sure there’s anything we can do about that. Hmmmm.

**Comment by vincode-io** [comment]
The NY Times app should also open on the iPhone. I've seen it an iOS bug where you have to delete and remove the app to get it correctly open the app.

I realize that this isn't the behavior that you would like, but this is just how iOS works. If you have an app that registers to handle its web links, the app will open instead of the site. It is the same as if you clicked a NY Times link in Safari.
