### ISSUE TITLE
Feature Request - Offline reading

### ISSUE THREAD

**Issue by Mickael-tinytap** [Ranchero-Software/NetNewsWire#3775]
Hi, I would like to add a feature that could be very useful, "Offline reading". 
I want to add an option to each article the possibility to mark it "Keep for offline reading". 
After reading the article, display an alert that ask to delete the article from the offline DB. 
Adding an option in the settings "Set offline reading for all new articles" with an expiration duration that will remove from the local DB after 3 days, 7 days, 1 month.

**Comment by stuartbreckenridge** [comment]
All articles in the NetNewsWire database are currently available for offline reading for around 90 days.

**Comment by brentsimmons** [comment]
Was there something else you meant by this? As Stuart writes, the app does save the contents of feeds for around 90 days.

**Comment by acrostich** [comment]
It would be helpful for an offline reading mode to cache images as well. It's useful to view images included in posts. Typical use cases are going where one doesn't have connectivity or where there's only expensive mobile data (e.g., when roaming abroad) so one can download all new new posts and images while on WiFi and read them later. This can be useful on both macOS and iOS though typical use cases are more common on iOS.

(Not sure if I should have instead created a new feature request instead of commenting on this one as my comment matches the subject but not fully the OP post. Apologies if I made the wrong choice.)

**Comment by vincode-io** [comment]
Image caching is in #1873, so this is a duplicate.
