### ISSUE TITLE
Sync via dropbox

### ISSUE THREAD

**Issue by rosolko** [Ranchero-Software/NetNewsWire#3831]
Hi, I have a question regarding the synchronization mechanism.

Is it possible to add synchronization of feeds with status (read/unread) via dropbox?
Password managers like keepass sync local database between devices this way.
Pretty fast and stable as far as I understand, it can help avoid icloud issues.

Thanks!

**Comment by brentsimmons** [comment]
I seriously doubt that would work. For syncing to work, it has to operate on rows of a database rather than an entire database file at a time.

For syncing, we support iCloud, Feedbin, Feedly, The Old Reader, FreshRSS, and more, and we strongly recommend trying one of those. (Some are for pay, and some are not. Some have free tiers. Some can even be self-hosted.)
