### ISSUE TITLE
Captcha handling for  Bloomberg feeds 

### ISSUE THREAD

**Issue by b-747** [Ranchero-Software/NetNewsWire#3868]
When accessing a free feed from Bloomberg I get blocked by their captcha verification

I’m using iPhone 11 / iOS 16.3/ NetNewsWire 6.1 (build 6110) 

 The feed:

https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss

the result 

![0ACE274D-F59D-4CD0-8A04-991BFE8B801B](https://user-images.githubusercontent.com/71388654/219229193-278c0b25-8f2a-4697-a15d-fddd3835e2e4.jpeg)

**Comment by brentsimmons** [comment]
The problem is that when you hit the Reader view button, it actually _is_ a robot reading that web page. Or a program, anyway, which is the same thing in this context.

The Reader view works by downloading the page and trying to figure out what the article text is. It’s a program doing that and not a person. Their captcha is working as expected.

I can’t imagine a way around this short of writing code that can fool the captcha, which seems unlikely.
