### ISSUE TITLE
Feature request: "Show only the title" alternative to "Number of lines"

### ISSUE THREAD

**Issue by amadejpapez** [Ranchero-Software/NetNewsWire#3870]
I often scroll through feeds and glance at the titles. With current options, they are either cut off or there is content showing beneath them.

![image](https://user-images.githubusercontent.com/63184600/219785040-8d1c741f-48c9-4ad2-ae38-d0a31e7478ab.jpeg)

I feel like "Show only the title" option would make my feed views look much more clean and nicer to look at. :)

**Comment by brentsimmons** [comment]
The way things work now is nice because it allows us to make each row the same height as the other rows, which we think makes for a nice and clean look.

If we showed entire titles, then we’d have variable-height rows, which is kind of a messy look. Some might even be quite long. (And then there’s the issue of what to do when an article doesn’t have a title.)

**Comment by amadejpapez** [comment]
@brentsimmons Yeah that makes sense. Thank you for replying! :D
