### ISSUE TITLE
Smart Feeds icon update

### ISSUE THREAD

**Issue by mantia** [Ranchero-Software/NetNewsWire#3886]
I would recommend three new icons for Smart Feeds:

**doc.text.image** for “Today”
**record.circle** for “Unread”
**star** for “Starred”

I would also recommend changing all of them to the NNW app’s tint color, rather than having different colors per.

**Comment by stuartbreckenridge** [comment]
If we are going to switch to NNW's app tint, can we tag #3865 to 6.2 as well?

**Comment by stuartbreckenridge** [comment]
Can we use `star.fill` on the timeline? The _empty_ star is used for Mark as Unstarred?

**Comment by mantia** [comment]
I recommend using star, not star.filled for the navigation element. I understand the concern that star is used for unstarred, though I don’t share that concern. However— it would be better for that to use star.slash instead.

star (not filled) should be the sidebar icon, as all the icons would share the same (unfilled) state, consistent with macOS applications on the platform.

**Comment by stuartbreckenridge** [comment]
I have updated the PR to cover this. 

There is a somewhat critical issue in `main` (#3806) that prevents adding/removing starred articles, but iOS is fine.

<img width="358" alt="Screenshot 2023-03-05 at 16 55 43" src="https://user-images.githubusercontent.com/7046652/222951171-fbf320ed-9f18-4347-9bf2-95376c10e894.png">
<img width="351" alt="Screenshot 2023-03-05 at 16 56 04" src="https://user-images.githubusercontent.com/7046652/222951200-2be47c59-1f53-4e35-8cfa-e4c5d85a5de5.png">
<img width="354" alt="Screenshot 2023-03-05 at 16 56 13" src="https://user-images.githubusercontent.com/7046652/222951205-43cfda7e-d903-4193-bc9d-4c906905ac51.png">
<img width="273" alt="Screenshot 2023-03-05 at 16 56 22" src="https://user-images.githubusercontent.com/7046652/222951206-5b436cd8-92c5-45e9-a2aa-9a298f98d025.png">
<img width="349" alt="Screenshot 2023-03-05 at 16 56 41" src="https://user-images.githubusercontent.com/7046652/222951210-2338fd0a-e0de-40e1-a5eb-4eaf9b914a1f.png">

**Comment by stuartbreckenridge** [comment]
@mantia / @brentsimmons On the timeline it does look a bit weird to have a filled circle for unread and an empty star for starred. Ditto for the icons when used in the navigation bar.

**Comment by stuartbreckenridge** [comment]
Furthermore, it’s a-ok to use star.fill on iOS. 

![IMG_1857](https://user-images.githubusercontent.com/7046652/222970904-e39b0f79-89df-4e13-8b31-95a1e88457e8.jpeg)

**Comment by vincode-io** [comment]
I've been traveling and am behind on what has been discussed in Slack. I saw this issue come up in email and thought it might be useful for me to comment without any Slack discussion context. Our users won't know about developer discussions either.

---

The new Today icon has me greatly confused. Is that a reference to the USA Today newspaper? I hope there is was some discussion around the using of a document icon to represent a time period, as I would like to understand the reasoning.

I don't know that the change to the Unread icon is an improvement or not. It looks like it reduces the contrast to the Read icon, which may make it less usable at a glance. The name change is good. It isn't like we had an "All Starred" feed or something.

Changing the open star icon to mean Starred instead of Unstarred is an interesting choice. I think if an app changed an icon to mean the opposite of what it did in the last release, I would first be confused and then be mad.

I'm also interested in why we are regressing to app tint color on the Smart Feed icons. I know most apps just use the app tint color, but it isn't like our Feed Icons are ever going to be monochrome. I remember when we add color to the Smart Feed icons and how much it brighter it made NetNewsWire feel.

----

I'm going to go and get caught up on the Slack discussions and hopefully there is something there that will better help me understand these suggestions.

**Comment by vincode-io** [comment]
I've read through the Slack discussion and now have context as to why we are making these changes.

I agree with @mantia that the Starred icon color could use some correcting. We didn't have a real designer pick the color and it shows.

Changing "All Unread" to "Unread" is a good decision.

I agree that the Today icon does need changing. The NNW team has gone back and forth on this several times and never come up with a good solution. If a document icon is better than anything else that we've previously discussed, I would like to understand why.

Beyond the icon, I personally would go even farther and agree with @mantia that the label needs changing as well. @brentsimmons is rightfully resistant to changing this, given the fact that it has been like this so long. Change typically makes people uncomfortable. In the software world we shouldn't make changes for the sake of change for this reason very reason.

That said, I think the Today label should be changed because it is misleading. The feeds that are present in the Today Smart Feed are for the last 24 hours, not for today. It has been a long time since someone was confused about this, but it still bugs me that it isn't an accurate label.

My suggestion is that we change Today to New and the icon something that is indicative that New means the last 24 hours. Here is a quick mockup I put together last time we had this discussion. I don't have any ownership over the color or the icon itself. I just think this is along the lines we should be thinking about.

![newnewswire-new](https://user-images.githubusercontent.com/16448027/222979790-5f8a0ef2-ddc5-4108-8fa2-70ba2a04dc2f.png)

**Comment by vincode-io** [comment]
I would also like to note that the proposed icons look much more balanced than the current ones. The current Today icon looks too weak compared to the other current ones. Any change to that icon or the others should take balance across the three into consideration.

**Comment by vincode-io** [comment]
Here is roughly what I would like to see. The Star color still needs some work. I haven't done any changes to it.

<img width="245" alt="Screenshot 2023-03-05 at 1 36 52 PM" src="https://user-images.githubusercontent.com/16448027/222981896-6cbbe1a3-9d1f-46ff-983e-a988a75991a9.png">

**Comment by mantia** [comment]
I want to first provide some context for those who do not know who I am (I don’t expect anyone to know who I am). I’ve been designing icons for 20 years. I’ve worked at Apple, the Iconfactory, and have run my own icon design studio (Parakeet) for the last 8 years. Though I recognize some people may feel varying degrees of ownership here, I believe I am uniquely qualified to make icon design suggestions for NNW. I filed this as an expert in this very specific niche field, not as a regular-old user.

I’m not interested in spending my time providing expert feedback on something where my design experience is going to be challenged, so if this topic is going to be debated, I think it’s best that I bow out.

I am happy to explain why these were chosen, but I do not want to participate in debate. Questions are awesome. But making suggestions outside of your area of expertise feels a little insulting.

<img width="200" alt="cleanshot_2023-02-28_at_09 07 35_2x" src="https://user-images.githubusercontent.com/4412247/223235080-ddb363a3-a520-4fa3-af85-ecc09be2e716.png">

**Comment by vincode-io** [comment]
@mantia I know who you are. Maybe you don't remember, but I've complemented you before on your work in the NNW Slack. I sincerely apologize if I came off as confrontational. That wasn't my intention and I have a lot of respect for you.

As a software developer with almost 30 years of experience, I don't feed like designing user interfaces is outside my realm of expertise. But, that is besides the point. I feel like any user, regardless of background, would have the same questions that I have.

If you would address the points that I raised and how you feel I missed the mark, I would consider it a teaching moment for myself. I don't think that people exchanging ideas needs to be confrontational or a debate. It is just trying to make the best product and learning from each other.

**Comment by brentsimmons** [comment]
Let’s use the icons that Louie proposes, and let’s use our regular tint color for all of them. The smart feed names will be changed to:

New
Unread
Starred

(The change to New allows us to make the time period of “new” configurable, if we choose to. There are people who might just launch NetNewsWire once a week, for instance, and they might want New to mean last 7 days, for instance.)

**Comment by stuartbreckenridge** [comment]
Can we address what we should do with the smaller icons used per article? Should these also be changing?

![image](https://user-images.githubusercontent.com/7046652/223281923-7d151d8f-fefc-4ac2-a631-d8e4d4e16329.jpeg)

![image](https://user-images.githubusercontent.com/7046652/223282064-89088798-2e92-44ed-80fe-51b0de4a260c.jpeg)

**Comment by stuartbreckenridge** [comment]
I would think that the unread indicator should change but that we should continue to use `star.fill`—similar to Mail's VIP—for the starred indicator?

**Comment by mantia** [comment]
@stuartbreckenridge I don’t think either should change for the article list. They should stay as-is.

**Comment by stuartbreckenridge** [comment]
OK. @brentsimmons Give me a bit of time with #3887 as I'll need to introduce `star.fill` _just_ for the timeline. 

@mantia A question: I have no issue with the icons being used, and the outline (non-filled) icons align us with Mail but, from both an iOS and macOS perspective, they are inconsistent with News (which I feel is our closest sidebar-like app). I feel there is an imbalance between outline icons for Smartfeeds vs. (what will generally be) filled icons for subscribed feeds. Thoughts?

<img width="211" alt="Screenshot 2023-03-08 at 20 26 13" src="https://user-images.githubusercontent.com/7046652/223713371-4d30e6f2-0f88-4988-8026-82c729788343.png">

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
