### ISSUE TITLE
Spacebar scrolling broken in macOS 13.3 beta

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3889]
Maybe it will get fixed for 13.3 final, but probably not. We probably need a work-around.

**Comment by cayla** [comment]
I would like to verify that the problem I am experiencing is this one.  <spacebar> advances to the next unread for me unless the article is larger than the viewport.  In that case, I need to scroll to the bottom of the article (I use the mousewheel) before <spacebar> advances again.  Is that what this issue is about?

I am on macOS 13.3 and that upgrade is when I started experiencing this as best I can recall and I am on NNW 6.1.2.

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.
