### ISSUE TITLE
Update thumbnails/avatars/etc. when screen scale changes

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#396]
Maybe just dump caches?

**Comment by vincode-io** [comment]
I did some brainstorming with @Wevah and these are some things that came up.

The current cache is global and only takes into consideration the screen with keyboard focus when the app is launched.  It doesn't handle moving to another screen with higher or lower density or opening additional windows on other density screens.

To have a 1 to 1 match between the icons and the screen scale, we would need to implement 2 or 3 caches or have per window caches instead of the global one.  We would also need to refresh the icons (reload cells) to pick up the new backing scale when the screen changes and also do something like change a per window cache (if we made one).

We think the better solution is to always cache and use the icons at 2x for Macs and 3x for iOS and then render them smaller on the less dense displays.  That way there is no UI reloading happening or caches that need to be dumped and rebuilt.  This will have a small performance impact on lower density displays as they will be working with larger images than they need to.
