### ISSUE TITLE
NetNewsWire attempts to access urls when opened in default browser

### ISSUE THREAD

**Issue by greggb** [Ranchero-Software/NetNewsWire#4011]
More of a question of behavior than a bug. When I have links set to open in the default browser Little Snitch still shows an access prompt for the url from NNW. I would think that clicking a link would skip access by NNW. Is it just the nature of how links are sent to the browser that Little Snitch would see NNW accessing the domain?

**Comment by danielpunkass** [comment]
I installed Little Snitch Version 5.6 (6281) to try to reproduce this with NetNewsWire Version 6.1.2 (6114), and I couldn't get the issue to appear. Auditing the code a bit it seems like there might be a bit of a different code path depending on the default browser and whether it's running at the time. Can you share some more details about your setup for instance what browser are you using? I tested with Safari.

**Comment by danielpunkass** [comment]
Actually I misread the bug originally. I thought you meant you were using the "Open In Browser" item for the feed itself. I reproduced the warning you described when clicking a link within the content of a post as rendered in NetNewsWire's web view. I suspect because this is going through WebKit that might explain the difference in behavior. I'll take a closer look.

**Comment by danielpunkass** [comment]
So, some interesting tidbits about this: the process that is making the request that actually triggers Little Snitch is not NetNewsWire per se, but the WebKit networking process that runs on NNW's behalf. The detailed info in Little Snitch confirms this:

<img width="461" alt="Screenshot 2023-06-01 at 6 31 42 PM" src="https://github.com/Ranchero-Software/NetNewsWire/assets/14606/8bdadfae-5541-4e8a-a57c-8b3777e2a79d">

I did some poking around in the networking process around the time a link is clicked and I suspect what is going on here is something inside WebKit called "preconnect" is causing it to fetch information about the clicked link, maybe as an optimization in case it is opened in the same web view, or maybe in order to ensure any redirects are managed before informing the WKWebView delegate about the resource that is going to be loaded?

There might not be much we can do about this, but maybe somebody will be able to dig deeper and find out whether it's possible to disable the WebKit "preconnect" behavior or otherwise try to prevent it accessing the URL directly before passing it on to the delegate.

**Comment by danielpunkass** [comment]
This line of code in WebKit's href clicking handler suggests there's a `linkPreconnectEnabled` setting on the document. If that could be disabled for NetNewsWire it seems like it would be ideal since the preconnects are not likely to be an efficient use of networking for NNW, where most links will be loaded in the browser or another web view.

**Comment by danielpunkass** [comment]
I was able to reproduce the same issue in MarsEdit, so I suspect this is a widespread default behavior for apps that use `WKWebView`.

**Comment by greggb** [comment]
@danielpunkass Thanks so much for the thorough investigation. It's really not blocking any kind of functionality or causing harm, just something I've noticed for a while and caused some head scratching. Happy to close this as 'working as Apple intends' or leave it open to see if maybe a tweak to `linkPreconnectEnabled ` would be useful.

**Comment by danielpunkass** [comment]
@greggb I appreciate you reporting it because it does seem like a situation where WebKit's default (I think) behavior is probably causing lots of false alarms for Little Snitch users. It might be something to try to work around from the app side, or maybe something to ask the Little Snitch developers about. Maybe they could finesse the behavior to at least explain that it's WebKit doing the loading on the app's behalf.
