### ISSUE TITLE
Reddit rss feeds are not importing

### ISSUE THREAD

**Issue by johnsturgeon** [Ranchero-Software/NetNewsWire#4044]
I'm currently moving my reddit feeds over to use their .rss protocol, and I'm having an issue with NetNewsWire not recognizing a feed URL:
https://www.reddit.com/r/technicalminecraft.rss

ReadKit works, as does Feedly

**Comment by brentsimmons** [comment]
I bet you also have the Reddit extension enabled. There’s a bug in our code — when the Reddit extension is enabled, you can’t add the RSS feeds.

You can deal with that by disabling the Reddit extension.

(Note: we will be removing the Reddit extension from the app soon, which will fix this bug, which is why I’m closing this.)

**Comment by johnsturgeon** [comment]
Thanks for the quick response.  Confirmed that worked!

**Comment by sashkab** [comment]
Oh, thanks for this bug report, was about to submit new one :)
