### ISSUE TITLE
Bug: Audio autoplays even though it shouldn't?

### ISSUE THREAD

**Issue by Shrinks99** [Ranchero-Software/NetNewsWire#4095]
### Context

[Recently I was reading a friend's blog post](https://inkdroid.org/2023/06/17/station-to-station/) with some audio elements that had `autoplay=""` attributes associated.  NetNewsWire seems to respect these (which I assume is default renderer behavior) while most other browsers have stopped doing this because... Well, autoplay is kind of annoying! 🙃 

### Reproduction Steps

1. Load a feed with audio tags that have `autoplay=""` attributes assigned to them
2. Navigate to the post
3. Audio autoplays :(

### More Info

Curiously, this already seems to be the intention judging by the following lines:

 https://github.com/Ranchero-Software/NetNewsWire/blob/9df917c0fb4d6fdbdc5b3f07c435ad275ab48046/Mac/MainWindow/Detail/DetailWebViewController.swift#L93

https://github.com/Ranchero-Software/NetNewsWire/blob/9df917c0fb4d6fdbdc5b3f07c435ad275ab48046/iOS/Article/WebViewController.swift#L526

Unsure why this isn't functioning as expected. :(

**Comment by GetToSet** [comment]
Hi @Shrinks99, thired these steps but I'm having trouble reproducing this issue since this blog post is too early and it's not listed in the RSS feed anymore.

I've tried loading the original page into NNW and could not reproduce this issue.

If you could build NNW from source, try launch a debug build, right click on the webview and open the inspector panel. Then type `location.href=https://inkdroid.org/2023/06/17/station-to-station/` to see if this issue exists when directly loading the original page.

**Comment by Shrinks99** [comment]
I recently ran across audio that _didn't_ autoplay and so unfortunately I'm completely unable to reproduce this.  Closing.  Will re-open if that changes.
