### ISSUE TITLE
Open article links in the NNW app browser

### ISSUE THREAD

**Issue by dbarros** [Ranchero-Software/NetNewsWire#4135]
Some feeds only show the title and maybe a snippet of text in NNW when clicking on an article. I can then click on the title in NNW and it'll open it in my preferred system web browser, where I then get to see the complete article.

Would it be possible to instead have the full article be shown inside of NNW? For example, when I click on the link marked as (1), open the Bloomberg article in-place:

![Screenshot 2023-10-14 at 12 12 57@2x](https://github.com/Ranchero-Software/NetNewsWire/assets/1286/2e332f31-df3d-4414-8a65-6f3a7fcf412f)

**Comment by brentsimmons** [comment]
Have you tried the Reader view? It’s the button in the toolbar to the left of the share button.

**Comment by dbarros** [comment]
When I click the Reader View, the contents change to this:

![Screenshot 2023-10-14 at 13 29 04@2x](https://github.com/Ranchero-Software/NetNewsWire/assets/1286/f31b5f75-1146-436e-a172-191a5a822cff)

What I was wanting (and I'm sorry if I'm not being clear), is to open any link that I click on that Techmeme NNW article view inside NNW. So looking at the screenshot above, if I click on _Xbox Wire_, I'd see this in NNW: 

<img width="1327" alt="image" src="https://github.com/Ranchero-Software/NetNewsWire/assets/1286/570c8cf8-e17d-4d2d-b904-66c379c59e17">

**Comment by stuartbreckenridge** [comment]
I played around briefly with enabling NNW to open in-article links in the app's `WKWebView` and encountered several issues.

First, there's no clean navigation _back_ to the original article. You have to deselect and reselect it to return to where you were.  Second, implementing `webView.goBack()` resulted in a white screen instead of returning to the feed article. 

And related to the above—on a Mac at least—enabling the WebView to load the article enabled `Forward` / `Back` right-click options on the Webview.  If you go to another article in the app, right-click and select `Forward` it actually loads the previously loaded external content (which was unexpected!). 

I think that, while it would be possible to load external links _inside_ NetNewsWire that's not really what it's for. It's a reader, not a browser.

**Comment by dbarros** [comment]
@stuartbreckenridge Thank you for responding in such detail. I guess my original query was a bit of hopeful thinking, knowing that the view is a WebView showing the article on the right.

The other reason was that, yes it's a reader, but it would be nice to be able do all my RSS reading in NNW itself -- which would include being able to see the full articles for those feeds that don't include it -- and not flip back-and-forth between it and a browser.

The issue you noticed where going `Forward` was taking you to the previously loaded external content could be avoided with some reset of the webview's browse history when switching articles. But now we'd be going down some hack-y rabbit hole.

**Comment by dbarros** [comment]
@stuartbreckenridge @brentsimmons Using NNW on iOS, I realised that it's doing what I'd like the Mac version to do. Or am I seeing it differently? The issues with going to previously loaded external sites when going `Forward` would not happen if the webview was recreated, and thus started on a clean slate, when switching between articles.

**Comment by brentsimmons** [comment]
I wrote a blog post about this issue in 2019: https://inessential.com/2019/09/04/on_the_many_netnewswire_feature_requests

Since that blog post appeared, we did add a Reader view — which (most of the time) works to provide full content when an article is truncated in a feed.
