### ISSUE TITLE
Feature request: Add feed option “Always use web view”. 

### ISSUE THREAD

**Issue by j0ra0** [Ranchero-Software/NetNewsWire#4166]
Today we can choose to always open a feed in reader mode. But for news sites with subscriptions this do not work well as it requires to log in. The only way to view the content is to open the web view, which right now adds an unnecessary extra click. 

Is it possible to add an option for each feed to “Always open web view” with in-app browser?

**Comment by j0ra0** [comment]
I’m using the iOS app

**Comment by Sma1lboy** [comment]
you mean always open reader view?

**Comment by j0ra0** [comment]
No, that’s already an option. 
I was thinking of an additional option to open in-app web browser view for a feed. This is how I read subscribed news content. Today I click the feed content and have to click one more time to open the web view to read the content as reader mode is not possible for content with paywall. It works, but it’s a bit annoying to not have the option to skip that extra click. 
However, an even better solution would be if the open reader view could use the cookie from the web view so the subscribed content is accessible to the reader mode.

**Comment by brentsimmons** [comment]
The issue is that your ad blockers and privacy extensions won’t run. A Mac in-app browser does _not_ inherit those things from Safari (or whatever browser you use), unfortunately.

To make matters worse, most people wouldn’t notice — because how could they? — that they’re being tracked on web pages viewed in NetNewsWire where their normal browser would block those trackers. It would be bad for privacy.
