### ISSUE TITLE
Make Text Size pref work for detail

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#42]

**Comment by vincode-io** [comment]
Do we want to add this to the General section of the Preferences?

Should we model this functionality on the System Settings [sidebar settings](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/#sidebars)?  I think it might be confusing if our small, medium, and large are different in font point for the Sidebar vs. Detail.   I don't see a problem with adding an XL size to that list.  In fact, I think we would want to since right now our Detail font size is about 33% bigger than the Sidebar by default.

**Comment by blackketter** [comment]
I _think_ this is the issue for a setting to adjust text size in NNW on macOS.
Just started using the b1 release (been waiting for Feedly support to arrive...)  Looks great.

Upon opening the app the first thing I went to change was the font size.  Instinctively I hit command-minus and command-equal, but to no avail.  Then looked in preferences, then came here.

So, count me as a strong vote for a global adjustable font size.  And another vote for the same keyboard shortcuts that Safari and Mail use.

**Comment by Wevah** [comment]
If this won't require 11.0, I can take this once details are worked out.

**Comment by brentsimmons** [comment]
Yes, we can model this on the sidebar settings.

The big trick here is to make this work with CSS — and do so in a way that people writing CSS themes for the detail view can use this as well. It might just be that we have to document some class names for theme writers, which they’ll need to support in order to support this feature.
