### ISSUE TITLE
Unread articles being removed

### ISSUE THREAD

**Issue by IronCraftMan** [Ranchero-Software/NetNewsWire#4222]
I have recently subscribed to a new feed, and I've been reading through the old articles in HTML form separately, while I have left NetNewsWire on my phone to (what I expect) store the new articles until I've caught up enough to read them. Unfortunately, it seems that NNW is only keeping the last 10 articles. This makes no sense, because I have a different feed for which I have at least 100 already read articles that are still stored. I would expect NNW to be deleting the read articles while keeping the unread ones. I have tried looking for settings, yet I can't seem to find anything related to deleting entries, read or unread.

**Comment by brentsimmons** [comment]
NetNewsWire does delete older articles, including unread articles — it doesn’t store them for all time (unless they’re starred), because you don’t want the database to grow forever.

How long it keeps older articles depends on the system you’re using (On my iPhone, iCloud, Feedly, Feedbin, etc.) — they each have their own rules.

**Comment by markcellus** [comment]
Yeah growing the database forever is a really quick way for performance to suffer. 👍

**Comment by IronCraftMan** [comment]
@brentsimmons It is just on my iPhone, no cloud syncing.
@markcellus I have over 2870 unread articles, and it's not any slower for me.

Why not provide an option for those of us who do not experience any issues with performance to not delete unread articles?
