### ISSUE TITLE
Fix iOS crash in -[UINavigationBar layoutSubviews] + 460 (UINavigationBar.m:3853)

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#4418]
Figured out how to reproduce, at least on some devices.

Go to article view. Tap link to open SFSafariViewController.

Rotate. Rotate again. Click Done. Crash.

**Comment by klanchman** [comment]
Since updating to 6.1.5 I’m seeing a crash that may be related. This is only on iPad, it seems not to crash on iPhone.

- Go to article view
- Open a link in Safari view controller
- Tap the toolbar button to open the page in Safari app
- Tap the back button in status bar to go back to NetNewsWire
- Tap “Done” (crash)

If unrelated I’m happy to open a new issue!

**Comment by brentsimmons** [comment]
I’m having so much trouble reproducing this. What kind of iPad are you using?

**Comment by klanchman** [comment]
Ah sorry, this is on an iPad Pro (11-inch) (4th generation) with iPadOS 18.2. In reproducing it again I found this is happening only in portrait orientation, not landscape. Also attached the ips if that helps!

[NetNewsWire-2024-12-22-193940.ips.zip](https://github.com/user-attachments/files/18223853/NetNewsWire-2024-12-22-193940.ips.zip)

**Comment by brentsimmons** [comment]
We have not seen this crash report since switching to the new UISplitViewController .tripleColumn style.
