### ISSUE TITLE
Drag Multiple Feeds from NNW 3.1.5 Receives only one

### ISSUE THREAD

**Issue by peternlewis** [Ranchero-Software/NetNewsWire#556]
If I select all my feeds in NNW 3.1.5 (yes, I am that person), and drag them to NNW 5, it accepts them all, but adds only one feed (after an prompt for information which it doesn't really need).

**Comment by brentsimmons** [comment]
NetNewsWire 5 doesn’t know what earlier versions of NetNewsWire write to the clipboard. If it did, it would know that you’re dragging feeds.

Instead, it just thinks you’re dragging in URLs — from a web page, for instance — and so it assumes you want to subscribe, but that the URL may not be of a feed, so it has to do the feed-finding process.

It picks just one of the URLs, because there’s no UI for finding multiple feeds at the same time.

WORKAROUND: export OPML from earlier versions of NetNewsWire and import in NetNewsWire 5.

**Comment by peternlewis** [comment]
I just dragged them over one at a time.  Just figured I'd report the issue.

**Comment by brentsimmons** [comment]
👍

**Comment by vincode-io** [comment]
I just ran into this too while implementing dragging from Feed Compass to NetNewsWire.

It might be nice if we bypass the add feed UI altogether when dragging to the sidebar (while still doing the feed-finding process).  I'm not sure how we would handle not found feeds in the UI though.  Maybe just a sheet that states "One or more feeds were invalid and not imported"?

**Comment by brentsimmons** [comment]
I think we need a drag type that says “YES THIS IS A FEED! DON’T BOTHER TO GO SEARCHING! TRUST ME!”

Older versions of NetNewsWire had this, I think. I’ll look into it.

**Comment by brentsimmons** [comment]
Closing this because NetNewsWire 3 hasn’t run on the last few macOS versions, and it’s unlikely people are still running across this issue. And there are other ways of bringing NNW3 subscriptions across — via OPML and via the `Import NNW3 Subscriptions…` command in the File menu.
