### ISSUE TITLE
Feature request: open in browser should work on multiple selection

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#857]

**Comment by hugolundin** [comment]
I have almost finished implementing this (pull request is coming soon), but need some guidance. 

Consider that the user selects multiple articles in the `TimelineView`. The first article selected will be marked as read – since it's shown in the `DetailView`. The consecutively selected ones are **not**, because its contents aren't shown in any view.

When opening these articles in the browser,  should they be marked as read or not? Is the general convention that opening an article in a browser considers it to have been read?

**Comment by brentsimmons** [comment]
Reopening because this needs additional verification.

**Comment by DavidMunch** [comment]
I can verify that it doesn't work per version 6.1.6 (6127). If you select more than one article, the menu option becomes greyed out, and the shortcut doesn't work as expected.

It would be very nice indeed to be able to select multiple article, and open them all at once, instead of having to do it manually for each article.

macOS 15.4.1.
