### ISSUE TITLE
Feature request: WebSub support for real-time feeds updates

### ISSUE THREAD

**Issue by skylex** [Ranchero-Software/NetNewsWire#878]
WebSub (formerly PubSubHubbub) is a simple protocol used by website owners to inform hubs of new content published on their RSS feeds, and hubs informs their subscribers of the new content via webhooks.

Implementation in NetNewsWire would mean maintaining servers which receives webhooks and informs users via websockets or similar, which means a lot of simultaneously open connections, so cost might be high.

Maybe this could lead to the creation of some kind of open standard where you could connect to any server offering (for free or not) this "push" service?

I think that's one of Twitter's main advantage, where websites automatically publish new Tweets about their new content and users can be instantly notified of new Tweets from anyone they want.

I reckon this may not be needed by most users, but the most content consuming users (amongst which may be news publishers themselves) might love this.

**Comment by bingoxo** [comment]
Any update on this ?

**Comment by brentsimmons** [comment]
Closing this because we’re not going to run servers — the cost is too much (not just monetary cost, but cost to write and maintain the server, deal with downtime, etc.).

If at some point there are some servers run by somebody else that NetNewsWire could use, we’d consider it and either reopen this ticket or create a new one.
