### ISSUE TITLE
When sidebar/toolbar is expanded/collapsed, VoiceOver announces the opposite of what happened

### ISSUE THREAD

**Issue by PeterSaathoff-Harshfield** [Ranchero-Software/NetNewsWire#935]
Reproduction steps:
1. Enable VoiceOver (command + F5)
2. Press [control + command + S] to show/hide the sidebar
3. Observe that VoiceOver announces the opposite
4. Press [option + command + T] to show/hide the toolbar
5. Observe that VoiceOver announces the opposite

Video:
https://youtu.be/6p9pDl6qVA4

Note: The same happens in Mail.app when its toolbar is shown/hidden, so this may be a MacOS bug.

**Comment by vincode-io** [comment]
I tested this and I am getting the opposite results as you are in your video.  Since the showing/hiding of the toolbar and sidebar given to us by the macOS frameworks, I'm going to say this is a macOS bug.

It looks like VoiceOver is reading the resulting menu options rather than the originating menu options.  Both of these two problems and the other issue you filed where we are marking read/unread have to do with shortcuts that change the text of the menu items.

I'm not sure at this point if there is anything we can do to help you.  It looks like it has something to do with your install of macOS since you are having the same problems as Mail.

We really appreciate excellent bug reports like this.  At this point, I'm not sure there is much we can do to help you.

**Comment by brentsimmons** [comment]
Clearing it from the milestone. Keeping it open in case we can find a way to reproduce it.
