### ISSUE TITLE
Relative image is not displayed

### ISSUE THREAD

**Issue by danielpunkass** [Ranchero-Software/NetNewsWire#954]
It appaers that site-relative images are not displayed correctly. For example, the NSHipster "Dark Mode on iOS 13" post:

https://nshipster.com/dark-mode/

Includes an image directly above "Dark Mode is an appearance preference". It renders as a missing image in NNW5:

<img width="943" alt="image" src="https://user-images.githubusercontent.com/14606/64181033-c8430480-ce33-11e9-9335-9e2399b33393.png">

Attaching NSHipsterRSS.txt representing the feed content as of today when that article is the most recent published entry.

[NSHipsterRSS.txt](https://github.com/brentsimmons/NetNewsWire/files/3569880/NSHipsterRSS.txt)

**Comment by RobFog** [comment]
Will this go into 5.0.4?

**Comment by vincode-io** [comment]
Turns out that this and #1280 need different fixes.

**Comment by pcr910303** [comment]
I'm guessing this fix isn't working b.c. `document.baseURI` isn't set to the location of the web page in NetNewsWire?

I first noticed this issue with the [SwiftUI defaults considered harmful](https://tonsky.me/blog/swiftui/) site, where the images have relative URLs. The first image's URL is https://tonsky.me/blog/swiftui/iphone.png, and `document.baseURl` is set to https://tonsky.me/blog/swiftui/. However the `DetailWebView`'s `<base>` element's source is set to https://tonsky.me/, hence wrongly resolving the relative URLs, which is causing all of the loading errors.

<table>
<tbody>
<tr><td><img width="556" alt="Screen Shot 2020-08-09 at 3 17 56 PM" src="https://user-images.githubusercontent.com/37990858/89726259-83681a80-da53-11ea-8c00-a1fe21036507.png"></td>
<td><img width="556" alt="Screen Shot 2020-08-09 at 3 28 38 PM" src="https://user-images.githubusercontent.com/37990858/89726383-03db4b00-da55-11ea-9a73-199a82fc87a2.png"></td></tr>
</tbody></table>

I tried to dig up the problem, but I wasn't successful: the `<base href="[[baseURL]]">` in page.html looks like it's getting rendered with [these substitutions](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Mac/MainWindow/Detail/DetailWebViewController.swift#L270), which looks like gets passed from the `Article` structure inside the state enum. It seems the `Article`s' `url` aren't set to the article's URL, but the feed's one?

I have more than enough enthusiasm to try fixing this problem (which personally bugs me a lot, and I'm learning a lot with the NetNewsWire's codebase), so I would love to help fixing this bug.

**Comment by brentsimmons** [comment]
@pcr910303 Go for it! You should join the Slack group and get on the #work channel.

**Comment by vincode-io** [comment]
@pcr910303 I assigned you to this issue since you expressed interest in working on it and we don't anyone to duplicate efforts.

**Comment by pcr910303** [comment]
A very preliminary, hacky patch that fixes this issue:
(I dislike the fact that the VC is making a URL object, I guess it should come from `ArticleRenderer`. That feels hacky..

```patch
diff --git a/Mac/MainWindow/Detail/DetailWebViewController.swift b/Mac/MainWindow/Detail/DetailWebViewController.swift
index e77101f9..72de8e18 100644
--- a/Mac/MainWindow/Detail/DetailWebViewController.swift
+++ b/Mac/MainWindow/Detail/DetailWebViewController.swift
@@ -263,7 +263,7 @@ private extension DetailWebViewController {
 		]
 		
 		let html = try! MacroProcessor.renderedText(withTemplate: ArticleRenderer.page.html, substitutions: substitutions)
-		webView.loadHTMLString(html, baseURL: ArticleRenderer.page.baseURL)
+		webView.loadHTMLString(html, baseURL: URL(string: rendering.baseURL) ?? ArticleRenderer.page.baseURL)
 	}
 
 	func fetchScrollInfo(_ completion: @escaping (ScrollInfo?) -> Void) {
diff --git a/Mac/MainWindow/Detail/page.html b/Mac/MainWindow/Detail/page.html
index 6d715390..51ea97d9 100644
--- a/Mac/MainWindow/Detail/page.html
+++ b/Mac/MainWindow/Detail/page.html
@@ -12,7 +12,6 @@
 				processPage();
 			})
 		</script>
-		<base href="[[baseURL]]">
 	</head>
 	<body>
 		[[body]]
diff --git a/Shared/Article Rendering/ArticleRenderer.swift b/Shared/Article Rendering/ArticleRenderer.swift
index 2dba5f84..aef969ae 100644
--- a/Shared/Article Rendering/ArticleRenderer.swift	
+++ b/Shared/Article Rendering/ArticleRenderer.swift	
@@ -52,7 +52,7 @@ struct ArticleRenderer {
 			self.baseURL = extractedArticle?.url
 		} else {
 			self.body = article?.body ?? ""
-			self.baseURL = article?.baseURL?.absoluteString
+			self.baseURL = article?.externalURL
 		}
 	}
 
```

**Comment by pcr910303** [comment]
@vincode-io I first asked this in the NNW slack #work, but it seems it's a bit hard to get an answer there due to the GitHub issue noise, so I'm asking here:

I'm trying to figure out why `<base>` was added in [page.html](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Mac/MainWindow/Detail/page.html#L15)
I first assumed it was for image & other asset loading, but then I just tried out to find out that by passing in the right URLs to [`webView.loadHTMLString`](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Mac/MainWindow/Detail/DetailWebViewController.swift#L276).
Which actually brings up my biggest question: why is `ArticleRenderer.page.baseURL` (which points to the page.html's file:// URL) getting passed into it?

**Comment by vincode-io** [comment]
@pcr910303 You have to pass the resources folder location to `loadHTMLString` so that it can load our local resources like CSS and JavaScript files.

**Comment by pcr910303** [comment]
@vincode-io Oh, I didn't realize that. Will just baking the contents of main.js and main_mac.js into the HTML file itself a tolerable solution? I personally think it's a failing fight to make the web view resolve a few links relative to the local html page, while some other links relative to the blog post page. But then if it's considered not an optimal solution I will try to find a better one.

**Comment by vincode-io** [comment]
@pcr910303 I'm sorry that I haven't been giving this the attention that it deserves.  I hadn't remembered until I read your post that we handle the image relative links by using JavaScript to convert them to absolute links.  I apologize for not pointing you to this sooner:

https://github.com/Ranchero-Software/NetNewsWire/blob/9362ea732c8bcdc080a68c163bcf7a6e3bfc7947/Shared/Article%20Rendering/main.js#L28

What this function does is it first fix any Feedbin images that we need to.  What is really important is this line:

https://github.com/Ranchero-Software/NetNewsWire/blob/9362ea732c8bcdc080a68c163bcf7a6e3bfc7947/Shared/Article%20Rendering/main.js#L32

So as long as our `document.baseURI` is correct we should be able to find the images.  We shouldn't need to adjust anything we are doing with `loadHTMLString`.

That said, is the `document.baseURI` correct?  It doesn't look like it in your Tonsky example.  When I inspect the page it says that it is `https://tonsky.me/` when we want it to be `https://tonsky.me/blog/swiftui`.  The code that makes the determination of what is in the `document.baseURI` is here:

https://github.com/Ranchero-Software/NetNewsWire/blob/9362ea732c8bcdc080a68c163bcf7a6e3bfc7947/Shared/Article%20Rendering/ArticleRenderer.swift#L295

This code looks to me that it does what we expect it to and has been around for a long time.  But, I did find something interesting while looking at the Tonsky blog.  This is the beginning of the entry for the blog post that we couldn't resolve the image for.

```html
    <entry>
      <title>SwiftUI defaults considered harmful</title>
      <link rel="alternate" type="text/html" href="https://tonsky.me/blog/swiftui/" />
      <id>https://tonsky.me/blog/swiftui/</id>
      <published>2020-01-20T00:00:00+00:00</published>
      <updated>2020-01-20T00:00:00+00:00</updated>
```

That has what we would expect the base URI to be in it.  What I don't know is if that is part of the Atom spec that we don't implement?  Maybe that is something we should be parsing and storing as part of the article if we don't already?

@brentsimmons Is this a part of the Atom spec you are familiar with?  If not, should @pcr910303 do some research and come up with a recommendation as to if we need to add this to `Article` or not?

**Comment by pcr910303** [comment]
> I'm sorry that I haven't been giving this the attention that it deserves.

No problem, I actually learnt a lot navigating the codebase, a valuable experience I would say.

> I hadn't remembered until I read your post that we handle the image relative links by using JavaScript to convert them to absolute links. 

I actually was aware of that - I thought it was the original fix of this problem. I think using JS to fix links is a failing fight though - there aren't just images, but there are videos, scripts (IIRC scripts aren't stripped in NNW, am I correct?), etc... trying to accommodate all of the edge cases will be hard IMHO. 

> That said, is the document.baseURI correct? It doesn't look like it in your Tonsky example. When I inspect the page it says that it is https://tonsky.me/ when we want it to be https://tonsky.me/blog/swiftui. 

Yup, that was the case because the value passed into the `<base>` tag is `Article.baseURL` which in this case has the value `https://tonsky.me`. I'm not sure if that's something expected or not. 

I'm still not sure if this really works though, b.c. `<base>` is global to the document (according to the [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)), which means the `<base>` tag should also interfere loading `main.js` and `main_mac.js`. But then for some reason the webview does load the JS files. Hmm...

> That has what we would expect the base URI to be in it. What I don't know is if that is part of the Atom spec that we don't implement? Maybe that is something we should be parsing and storing as part of the article if we don't already?

I didn't read the parsing code, so I can't say in confidence, but if I'm guessing right, it's `Article.externalURL`. I basically just added a breakpoint to the rendering code, printed out the article object to find what I need, so there might be a better property that I don't know. But my patch is just making a `URL` from it and passing it to the webview as the `baseURL`.

**Comment by vincode-io** [comment]
There might be a solution where we don't have to use that JavaScript code to fix the links.  I'm certainly open to it.  I see your point that it will be difficult to fix every resource, but it should be possible to hit the main ones if we have to.

Regarding how the `<base>` tag works with WKWebView, I'm frankly not sure.  It doesn't look like it has any impact at all from what I've seen or we wouldn't need the JavaScript hack.  Maybe you could figure it out and let us know?

`Article.externalURL` is from the JSON RSS spec where blogs like Daring Fireball which are linkblogs can link out to the article that they are commenting on.  I'm pretty sure that we don't have any way to specify a different document root on a per article basis.

**Comment by pcr910303** [comment]
@vincode-io Good news, I think I have a one-line patch that fixes all of these problems, and doesn't feel like a big hack.

> Regarding how the <base> tag works with WKWebView, I'm frankly not sure. It doesn't look like it has any impact at all from what I've seen or we wouldn't need the JavaScript hack. Maybe you could figure it out and let us know?

It definitely does have impact, since from what I see here it did try to load images relatively to `https://tonsky.me`.
I did some experiments, and it seems that WKWebView loads resources that are encountered prior to `<base>` relative to the webview's `baseURL`, while the ones encountered after `<base>` are loaded relatively to `document.baseURI`. So I just decided that if we can fix the `baseURL` we can fix this.

> Article.externalURL is from the JSON RSS spec where blogs like Daring Fireball which are linkblogs can link out to the article that they are commenting on. I'm pretty sure that we don't have any way to specify a different document root on a per article basis.

I decided that NNW can just go best-effort and use the URL that the title usually points to, which is `Article.preferredLink`. Which means that replacing one line of ArticleRenderer will fix it, below is the patch.

```patch
diff --git a/Shared/Article Rendering/ArticleRenderer.swift b/Shared/Article Rendering/ArticleRenderer.swift
index 2dba5f84..3106690c 100644
--- a/Shared/Article Rendering/ArticleRenderer.swift	
+++ b/Shared/Article Rendering/ArticleRenderer.swift	
@@ -52,7 +52,7 @@ struct ArticleRenderer {
 			self.baseURL = extractedArticle?.url
 		} else {
 			self.body = article?.body ?? ""
-			self.baseURL = article?.baseURL?.absoluteString
+			self.baseURL = article?.preferredLink
 		}
 	}
 
```

**Comment by pcr910303** [comment]
@brentsimmons May I ask how it's going? I would love to incorporate the change...

**Comment by brentsimmons** [comment]
I will try to get to this tonight — I just haven’t had time yet (sorry about that!)

**Comment by brentsimmons** [comment]
Finally looking at this now…

**Comment by brentsimmons** [comment]
The bug is in the Atom parser — RSAtomParser.addLink (in RSParser.framework).

Here’s what is happening:

NetNewsWire prefers to use the permalink for a given article as the base URL. An Article has two URL properties, both optional:

* url: permalink to the page
* externalURL: link to some other page

In ArticleRenderer, we’ve extended Article with a baseURL property, which looks at the url property first, is it should. (It looks at fallbacks when url is nil.)

Here’s the bug: url is nil in this case. The URL we want to use as baseURL is incorrectly stored in externalURL.

And that’s happening because, in RSAtomParser.addLink, we’re treating `related` links as permalinks, when we should be treating `alternate` links as permalinks. We’ve got it backwards in the code!

Note: RSAtomParser doesn’t use Article as a type: instead it uses `RSParsedArticle`, which has link and permalink properties.

RSParsedArticle.permalink is the same as Article.url
RSParsedArticle.link is the same as Article.externalURL
