### ISSUE TITLE
Unread articles disappearing

### ISSUE THREAD

**Issue by sgoodwin** [Ranchero-Software/NetNewsWire#961]
I have some older articles I was keeping marked as unread for when I had time to sit down and watch them more thoroughly (they're from my youtube rss feed), but they seem to have disappeared, I guess because the articles are old?

In theory, if the articles are being stored locally, these should not disappear even though they're too old to show in the RSS feed, no?

**Comment by danielpunkass** [comment]
Sort of tangential to this: I found it confusing that many of my feeds, which have not been updated in months or years sometimes, show zero articles instead of showing me the latest from way back when.

**Comment by brentsimmons** [comment]
NetNewsWire doesn’t keep articles forever. Even unread articles.

Part of this is so that unread counts don’t turn astronomical.

Another part is so that the database of articles doesn’t get to a size where it takes substantial disk space — and app performance suffers.

(NetNewsWire isn’t alone in this: it’s pretty normal. For instance, Google Reader used to stop tracking read/unread status after 30 days.)

Another way of looking at it: NetNewsWire is not meant as as permanent archive of articles. It really is for recent news.

**Comment by Alex-Vasile** [comment]
I would like to add my two cents. This caught me by surprise since there's no mention of this behaviour anywhere in the app, and I also find the fact that it does this painful.

I am using this as a reading list for my RSS feeds and I tend to cycle through which of my different feeds I am currently reading from. When this ends up meaning is that I am now forced to stay ontop of articles and keep adding them to Safari's reading list when I can see that they're getting close to top of the list in the app.

Having to manually save the articles to my safari reading list defeats half the purpose that I had for using the app in the first place, I started with safari and wanted some better organization.

**Comment by vincode-io** [comment]
Here is our policy for future reference. 

https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown
